[package]
name = "fjfj-bazel-compat"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
ariadne.workspace = true
base64.workspace = true
chumsky.workspace = true
clap.workspace = true
fjfj-graph.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
