load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "fjfj-cli",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "fjfj_cli",
    edition = "2024",
    version = "0.0.1",
    deps = ["@crates//:anyhow", "@crates//:clap", "@crates//:serde_json", "@crates//:thiserror", "@crates//:tokio", "@crates//:tracing", "//crates/fjfj-bazel-compat", "//crates/fjfj-bzlmod", "//crates/fjfj-exec", "//crates/fjfj-graph", "//crates/fjfj-remote", "//crates/fjfj-starlark", "//crates/fjfj-telemetry", ],
)

rust_test(
    name = "fjfj-cli_test",
    crate = ":fjfj-cli",
    data = ["//crates/fjfj-bzlmod/tests/fixtures"],
)
