[package]
name = "fjfj-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
fjfj-bazel-compat.workspace = true
fjfj-bzlmod.workspace = true
serde_json.workspace = true
fjfj-starlark.workspace = true
fjfj-graph.workspace = true
fjfj-exec.workspace = true
fjfj-remote.workspace = true
fjfj-telemetry.workspace = true
