#!/usr/bin/env python3
"""Writes ../src/native_rules.rs from native_rules.json (see native_rules.py)."""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "native_rules.json")))

# Written by hand in rule.rs and checked against Bazel there.
HAND = {"filegroup", "alias"}

TYPES = {
    "STRING": "String",
    "BOOLEAN": "Bool",
    "STRING_LIST": "StringList",
    "LABEL_LIST": "LabelList",
    "LICENSE": "StringList",
    "STRING_DICT": "StringDict",
    "LABEL_LIST_DICT": "LabelListDict",
    "LABEL": "Label",
    "LABEL_KEYED_STRING_DICT": "LabelKeyedStringDict",
    "OUTPUT_LIST": "OutputList",
    "TRISTATE": "Tristate",
    "INTEGER": "Int",
}
# Names whose proto type says list of strings but whose schema type is labels.
LABELS = {"visibility", "transitive_configs"}
DICTS = {"STRING_DICT", "LABEL_LIST_DICT", "LABEL_KEYED_STRING_DICT"}
LISTS = {"STRING_LIST", "LABEL_LIST", "LICENSE"}


def rust_str(s):
    return json.dumps(s)


def default(a, mandatory, given):
    ty = a["type"]
    if mandatory:
        return None
    if a["name"] in given:
        # Set only to make the rule load (`size` of a test); the class has none.
        return {"STRING": "D::EmptyString", "BOOLEAN": "D::False"}.get(ty, "D::EmptyList")
    if a["name"] in LABELS:
        return "D::EmptyList"
    if not a["shown"]:
        return "D::Unset"
    if ty == "STRING":
        v = a.get("stringValue", "")
        return "D::EmptyString" if v == "" else f"D::Str({rust_str(v)})"
    if ty == "BOOLEAN":
        return "D::True" if a.get("booleanValue") else "D::False"
    if ty in ("INTEGER", "TRISTATE"):
        return f"D::Int({a.get('intValue', 0)})"
    if ty in LISTS:
        vals = a.get("stringListValue")
        if vals:
            return "D::Strs(&[" + ", ".join(rust_str(v) for v in vals) + "])"
        return "D::EmptyList"
    if ty in DICTS:
        return "D::EmptyDict"
    return "D::Unset"


def attrs_of(cls, v):
    mandatory = set(v["mandatory"])
    by_name = {a["name"]: a for a in v["attributes"]}
    order = [n for n in (v["order"] or []) if n not in ("name", "kind")]
    rest = [a["name"] for a in v["attributes"] if a["name"] not in order and a["name"] != "name"]
    lines = []
    for name in order + rest:
        a = by_name.get(name)
        if a is None:
            continue
        ty = "LabelList" if name in LABELS else TYPES[a["type"]]
        # `existing_rule` shows the default as text, but the attribute is a
        # label (`bazel query --output=xml` shows <label> and a rule-input).
        if cls in ("label_flag", "label_setting") and name == "build_setting_default":
            ty = "Label"
        if name in mandatory:
            lines.append(f'        m({rust_str(name)}, {ty}),')
        else:
            lines.append(f'        a({rust_str(name)}, {ty}, {default(a, False, v["given"])}),')
    return lines


def const_name(cls):
    return cls.upper()


out = []
out.append("// @generated by crates/fjfj-graph/probes/gen_native_rules.py from native_rules.json.")
out.append("// Do not edit: rerun native_rules.py (against Bazel 9.2.0), then the generator.")
out.append("//")
out.append("//! The native rule classes of Bazel 9.2.0 other than `filegroup` and `alias`,")
out.append("//! with the attributes each takes: what a BUILD file may set, its type, its default")
out.append("//! and whether it is mandatory.")
out.append("")
out.append("use crate::rule::{AttrDefault as D, AttrType::*, RuleClass, a, m};")
out.append("")
names = []
removed = []
for cls in sorted(data):
    v = data[cls]
    if cls in HAND:
        continue
    if v.get("error") == "removed":
        removed.append(cls)
        continue
    if "error" in v:
        continue
    names.append(cls)
    out.append(f"pub static {const_name(cls)}: RuleClass = RuleClass {{")
    out.append(f"    name: {rust_str(cls)},")
    out.append("    attrs: &[")
    out.extend(attrs_of(cls, v))
    out.append("    ],")
    out.append("};")
    out.append("")
out.append("/// The native rule classes this file has.")
out.append("pub const CLASSES: &[&RuleClass] = &[")
for cls in names:
    out.append(f"    &{const_name(cls)},")
out.append("];")
out.append("")
out.append("/// Rules Bazel 9.2.0 still names but has removed: calling one fails and asks for a `load()`.")
out.append("pub const REMOVED: &[&str] = &[")
for cls in removed:
    out.append(f"    {rust_str(cls)},")
out.append("];")
open(os.path.join(HERE, "..", "src", "native_rules.rs"), "w").write("\n".join(out) + "\n")
print(len(names), "classes,", len(removed), "removed")


# The Starlark functions that call them.
fns = []
fns.append("// @generated by crates/fjfj-graph/probes/gen_native_rules.py from native_rules.json.")
fns.append("// Do not edit: rerun native_rules.py (against Bazel 9.2.0), then the generator.")
fns.append("//")
fns.append("//! The functions of the native rules in `fjfj_graph::native_rules`, which a BUILD file calls")
fns.append("//! as globals and a `.bzl` as `native.<rule>`.")
fns.append("")
fns.append("use crate::args::fatal;")
fns.append("use crate::instantiate::{call_rule, native_schema};")
fns.append("use fjfj_graph::native_rules;")
fns.append("use starlark::environment::GlobalsBuilder;")
fns.append("use starlark::eval::{Arguments, Evaluator};")
fns.append("use starlark::starlark_module;")
fns.append("use starlark::values::none::NoneType;")
fns.append("")
fns.append("const REMOVED: &str = \"\\n         This rule has been removed from Bazel. Please add a `load()` statement for it.\\n         This can also be done automatically by running:\\n         buildifier --lint=fix <path-to-BUILD-or-bzl-file>\\n         \";")
fns.append("")
fns.append("#[starlark_module]")
fns.append("pub(crate) fn generated_native_rules(builder: &mut GlobalsBuilder) {")
for cls in names:
    fns.append(f"    fn {cls}<'v>(")
    fns.append("        args: &Arguments<'v, '_>,")
    fns.append("        eval: &mut Evaluator<'v, '_, '_>,")
    fns.append("    ) -> starlark::Result<NoneType> {")
    fns.append(f"        call_rule(&native_schema(&native_rules::{const_name(cls)}), {rust_str(cls)}, None, args, eval)")
    fns.append("    }")
for cls in removed:
    fns.append(f"    fn {cls}<'v>(")
    fns.append("        #[allow(unused_variables)] args: &Arguments<'v, '_>,")
    fns.append("    ) -> starlark::Result<NoneType> {")
    fns.append("        Err(fatal(REMOVED))")
    fns.append("    }")
fns.append("}")
open(os.path.join(HERE, "..", "..", "fjfj-starlark", "src", "native_rule_fns.rs"), "w").write("\n".join(fns) + "\n")
