[package]
name = "fjfj-starlark"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
allocative.workspace = true
stacker.workspace = true
num-bigint.workspace = true
starlark_derive.workspace = true
fjfj-graph.workspace = true
fjfj-loading.workspace = true
starlark.workspace = true
starlark_syntax.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
