load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "fjfj",
    srcs = ["src/main.rs"],
    edition = "2024",
    version = "0.0.1",
    deps = [
        "//crates/fjfj-cli",
    ],
)

rust_test(
    name = "sandbox_helper_test",
    srcs = ["tests/sandbox_helper.rs"],
    data = [":fjfj"],
    edition = "2024",
    deps = ["@crates//:tempfile"],
)
