//! Making repositories: running the module extensions a module graph uses
//! and the repository rules they (and `use_repo_rule`) name, in a directory
//! of the caller's choosing (buildfiji-mum.8.4).
//!
//! This is the driver that joins the module graph (`fjfj-bzlmod`) to the
//! Starlark that runs ([`fjfj_starlark::run_module_extension`],
//! [`fjfj_starlark::run_repository_rule`]). It handles extensions defined in
//! the main repository and in the other modules of the graph, whose
//! repositories are made on demand (buildfiji-mum.8.4, buildfiji-lfe): a
//! repository is made when something first needs a file of it, which for
//! one an extension generates means running the extension first.
//!
//! What Bazel 9.2.0 does, all read off probes of `bazel fetch`:
//!
//! - An extension is run once, over every usage of it, when one of the
//!   repositories it generates is wanted. A repository it generates is named
//!   `<repo of the .bzl>+<extension>+<name>`: `+ext+a` for an extension in
//!   the main repository, `rules_java++toolchains+local_jdk` for one in
//!   `rules_java`.
//! - What the root module imports with `use_repo` must be generated by the
//!   extension: `module extension @@//:ext.bzl%ext does not generate
//!   repository "zzz", yet it is imported as "zzz" in the usage at
//!   MODULE.bazel:2:20`. Imports are checked in order, after the
//!   implementation has run.
//! - An extension's working directory is `modextwd/<repo prefix>` in the
//!   output base, and a generated repository is made in `external/<name>`.

mod credentials;
#[cfg(test)]
mod driver_tests;
mod http;
#[cfg(test)]
mod http_archive_matrix;
#[cfg(test)]
mod http_archive_tests;
#[cfg(test)]
mod lock_matrix;
#[cfg(test)]
mod lock_tests;
#[cfg(test)]
mod multi_matrix;
#[cfg(test)]
mod multi_tests;
#[cfg(test)]
mod package_error_tests;
#[cfg(test)]
mod replay_matrix;
#[cfg(test)]
mod replay_tests;
#[cfg(test)]
mod resolve_tests;
mod tools;

pub use credentials::{CredentialHelper, CredentialHelpers, Headers};
pub use http::HttpDownloader;
pub use tools::{BAZEL_TOOLS_ARCHIVE, materialize_bazel_tools};

use fjfj_bzlmod::extension_repos::{ExtensionInstance, normalized_bzl};
use fjfj_bzlmod::lockfile::Json;
use fjfj_bzlmod::overrides::RepoRule;
use fjfj_bzlmod::registry::Registry;
use fjfj_bzlmod::{Module, ModuleKey, Resolution};
use fjfj_graph::Label;
use fjfj_loading::PackageLookup;
use fjfj_starlark::{
    BzlLoader, Downloader, ExtensionInput, FactValue, GeneratedRepo, MetaDeps, MetadataOut,
    ModuleUse, RecordedInput, RepoAttr, RepoEnv, RepoMappings, RepoProvider, TagUse, TagValue,
    convert_repo_attrs, has_module_extension, has_repository_rule, repository_rule_defaults,
    repository_rule_is_local, run_module_extension, run_repository_rule,
};
use starlark::PrintHandler;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, OnceLock, Weak};

/// Why a repository could not be made: Bazel's message for it.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{message}")]
pub struct FetchError {
    pub message: String,
}

/// The lookup of the repo rooted at `root`: its `.bazelignore` and the
/// `ignore_directories()` of its `REPO.bazel`. `whose` completes Bazel's
/// `error evaluating REPO.bazel file for ...`.
fn lookup_at(root: &Path, whose: &str) -> Result<PackageLookup, FetchError> {
    let lookup = PackageLookup::new(root).map_err(|e| FetchError {
        message: e.to_string(),
    })?;
    let file = root.join("REPO.bazel");
    let text = match std::fs::read_to_string(&file) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(lookup),
        Err(e) => return failed(format!("{}: {e}", file.display())),
    };
    match fjfj_starlark::evaluate_repo_file(&file.display().to_string(), &text, whose) {
        Ok(repo_file) => Ok(lookup.with_ignore_directories(repo_file.ignore_directories)),
        Err(e) => {
            // The caller puts `ERROR: ` before the first line.
            let mut lines: Vec<String> = e
                .events
                .iter()
                .map(|event| match event.starts_with("DEBUG: ") {
                    true => event.clone(),
                    false => format!("ERROR: {event}"),
                })
                .collect();
            lines.push(format!("ERROR: {}", e.summary));
            let first = lines[0]
                .strip_prefix("ERROR: ")
                .unwrap_or(&lines[0])
                .to_owned();
            lines[0] = first;
            failed(lines.join("\n"))
        }
    }
}

fn failed<T>(message: impl Into<String>) -> Result<T, FetchError> {
    Err(FetchError {
        message: message.into(),
    })
}

/// What making the repositories of a workspace needs.
pub struct Options {
    /// The main repository's directory.
    pub workspace_root: PathBuf,
    /// Where extensions work (`modextwd`) and repositories are made
    /// (`external`).
    pub output_base: PathBuf,
    /// The client's environment.
    pub environ: BTreeMap<String, String>,
    /// How `http` and `https` URLs are fetched; none means they cannot be.
    pub downloader: Option<Arc<dyn Downloader>>,
    /// The repository cache directory, which holds `content_addressable/`.
    pub repository_cache: Option<PathBuf>,
    /// `--distdir`: where a download's file may be found by its name.
    pub distdirs: Vec<PathBuf>,
    /// The registries the modules of the graph came from: how a module's
    /// repository is made is in its `source.json`.
    pub registries: Vec<Registry>,
    /// The `facts` a previous run kept, as the lockfile has them: an extension's
    /// id (`//:ext.bzl%name`) and its facts as a JSON object.
    pub facts: Vec<(String, Json)>,
    /// `--override_repository`: the name the main repository sees a repo by,
    /// and the directory that is the repo instead (relative to the workspace).
    pub repo_overrides: Vec<(String, PathBuf)>,
}

/// A repository to make: a rule and what it is called with.
struct Generated {
    repo: GeneratedRepo,
    /// What a `use_repo_rule` call or a module's source gave, not yet read as
    /// the rule's types: that needs the rule's `.bzl` loaded.
    raw_attrs: Option<Vec<(String, TagValue)>>,
    /// The extension that made it, `@@//:ext.bzl%ext`; empty for a module's
    /// own repository and for a `use_repo_rule`.
    extension: String,
}

#[derive(Default)]
struct State {
    /// What each repo calls the others; grows as extensions run.
    mappings: Arc<RepoMappings>,
    /// The repositories that have been made, by canonical name.
    lookups: HashMap<String, Arc<PackageLookup>>,
    /// Repositories extensions generated, by canonical name.
    generated: BTreeMap<String, Generated>,
    /// The extensions that have run, and those running now.
    ran: BTreeSet<usize>,
    running: BTreeMap<usize, std::thread::ThreadId>,
    /// Repositories being made now, and by which thread.
    making: BTreeMap<String, std::thread::ThreadId>,
    /// Repos replaced by a directory, by canonical name.
    overridden: BTreeMap<String, PathBuf>,
    /// What each extension that ran gives `MODULE.bazel.lock`.
    locked: Vec<LockedExtension>,
    /// What the lockfile of the last run had for extensions: a run whose
    /// inputs have not changed is not made again.
    previous: Vec<LockedExtension>,
    /// The `facts` extensions kept, by extension id.
    facts: Vec<(String, Json)>,
    /// What was worth a warning, each as Bazel words it after `WARNING: `.
    warnings: Vec<String>,
}

/// One extension's entry in `MODULE.bazel.lock`'s `moduleExtensions`.
#[derive(Debug, Clone, PartialEq)]
pub struct LockedExtension {
    /// `//:ext.bzl%name`, or `@@repo//:ext.bzl%name` from another repository.
    pub id: String,
    /// `general`, or `os:linux`, `arch:amd64`, `os:linux,arch:amd64` for an
    /// extension that depends on them.
    pub factors: String,
    /// What goes under the factors: `bzlTransitiveDigest`, `usagesDigest`,
    /// `recordedInputs` and `generatedRepoSpecs`.
    pub entry: Json,
}

struct Inner {
    options: Options,
    resolution: Resolution,
    extensions: Vec<ExtensionInstance>,
    loader: OnceLock<BzlLoader>,
    state: Mutex<State>,
    /// Signalled when a repository or extension stops being made, for the
    /// threads that wait for it.
    progress: std::sync::Condvar,
    /// What extensions and rules print, in order, until the call that made
    /// them hands it on.
    prints: Prints,
    /// What went wrong in the packages loaded, until [`Repos::take_events`].
    events: Mutex<Events>,
}

/// The errors of packages, each said once: a BUILD file is read again for each
/// phase that wants it.
#[derive(Default)]
struct Events {
    queue: Vec<String>,
    seen: std::collections::HashSet<String>,
}

impl Events {
    fn push(&mut self, event: String) {
        if self.seen.insert(event.clone()) {
            self.queue.push(event);
        }
    }

    fn extend(&mut self, events: impl IntoIterator<Item = String>) {
        for event in events {
            self.push(event);
        }
    }
}

/// What was printed, kept for whoever asked for the work: an extension may
/// run because a file was loaded, far from the call that has a print handler.
#[derive(Default)]
struct Prints(
    Mutex<Vec<String>>,
    /// The packages whose BUILD files printed already: one is read again for
    /// each phase that wants it, and prints once.
    Mutex<std::collections::HashSet<(String, String)>>,
);

impl PrintHandler for Prints {
    fn println(&self, text: &str) -> starlark::Result<()> {
        self.0.lock().unwrap().push(text.to_owned());
        Ok(())
    }

    fn println_at(
        &self,
        location: Option<&starlark::codemap::FileSpan>,
        text: &str,
    ) -> starlark::Result<()> {
        self.println(&fjfj_starlark::print_line(location, text))
    }
}

impl Prints {
    /// Hand everything printed so far to `print`.
    fn hand_on(&self, print: Option<&dyn PrintHandler>) {
        let printed = std::mem::take(&mut *self.0.lock().unwrap());
        if let Some(print) = print {
            for text in printed {
                let _ = print.println(&text);
            }
        }
    }
}

struct Provider(Weak<Inner>);

impl RepoProvider for Provider {
    fn lookup(&self, repo: &str) -> Result<Option<Arc<PackageLookup>>, String> {
        let inner = self.0.upgrade().ok_or("the repositories are gone")?;
        inner.lookup(repo).map_err(|e| e.message)
    }

    fn mappings(&self) -> Arc<RepoMappings> {
        match self.0.upgrade() {
            Some(inner) => inner.state.lock().unwrap().mappings.clone(),
            None => Arc::default(),
        }
    }

    fn module(&self, repo: &str) -> Option<(String, String)> {
        let inner = self.0.upgrade()?;
        inner
            .resolution
            .selection
            .resolved
            .iter()
            .find(|(key, _)| {
                if key.is_root() {
                    repo.is_empty()
                } else {
                    inner.resolution.canonical_name_of(key) == repo
                }
            })
            .map(|(key, module)| {
                let name = if key.is_root() {
                    module.name.clone()
                } else {
                    key.name.clone()
                };
                (name, key.version.to_string())
            })
    }
}

/// The repositories of a workspace.
pub struct Repos {
    inner: Arc<Inner>,
}

fn label_text(label: &Label) -> String {
    format!("@@{}//{}:{}", label.repo, label.package, label.name)
}

/// The label of `//pkg:file.bzl` in `repo`.
fn bzl_label(repo: &str, rest: &str) -> Label {
    let rest = rest.strip_prefix("//").unwrap_or(rest);
    let (package, name) = rest.split_once(':').unwrap_or(("", rest));
    Label {
        repo: repo.to_owned(),
        package: package.to_owned(),
        name: name.to_owned(),
    }
}

impl Repos {
    /// The repositories of the workspace whose root module is `root`, and
    /// which has no other module.
    pub fn new(options: Options, root: Module) -> Result<Repos, FetchError> {
        Repos::from_resolution(options, Resolution::root_only(root))
    }

    /// The repositories of the workspace whose module graph is `resolution`.
    pub fn from_resolution(options: Options, resolution: Resolution) -> Result<Repos, FetchError> {
        // A `//...` walk does not enter the convenience symlinks, which lead into
        // the output base: `bazel-bin`, `bazel-out`, `bazel-testlogs` and
        // `bazel-<workspace>`.
        let workspace_dir = options
            .workspace_root
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default();
        let lookup = lookup_at(&options.workspace_root, "the main repo")?
            .with_skipped_root_dirs([
                "bazel-bin".to_owned(),
                "bazel-out".to_owned(),
                "bazel-testlogs".to_owned(),
                "bazel-genfiles".to_owned(),
                format!("bazel-{workspace_dir}"),
            ])
            .with_skipped_root_dirs(links_into(&options.workspace_root, &options.output_base));
        // `@bazel_tools` is served from the output base, where its files are put.
        let tools_dir = options.output_base.join("external").join("bazel_tools");
        materialize_bazel_tools(&tools_dir).map_err(|e| FetchError {
            message: format!("cannot write @bazel_tools to {}: {e}", tools_dir.display()),
        })?;
        let tools_lookup = PackageLookup::new(&tools_dir).map_err(|e| FetchError {
            message: e.to_string(),
        })?;
        let mut mappings = RepoMappings::from_repos(resolution.repo_mappings());
        if !resolution.selection.keys().any(|k| k.name == "bazel_tools") {
            mappings.insert(
                "bazel_tools",
                [("bazel_tools".to_owned(), "bazel_tools".to_owned())],
            );
        }
        let extensions = resolution.extensions();
        // The names are the main repository's, and an empty one names nothing.
        let mut overridden = BTreeMap::new();
        for (name, path) in &options.repo_overrides {
            if name.is_empty() {
                continue;
            }
            let Some(canonical) = mappings.find_apparent("", name) else {
                return failed(format!(
                    "no repository visible as '@{name}' from the main repository, but overridden \
                     with --override_repository. Use --inject_repository to add new repositories."
                ));
            };
            overridden.insert(canonical, options.workspace_root.join(path));
        }
        let mut state = State {
            mappings: Arc::new(mappings),
            overridden,
            ..State::default()
        };
        state.lookups.insert(String::new(), Arc::new(lookup));
        state
            .lookups
            .insert("bazel_tools".to_owned(), Arc::new(tools_lookup));
        let inner = Arc::new(Inner {
            options,
            resolution,
            extensions,
            loader: OnceLock::new(),
            state: Mutex::new(state),
            progress: std::sync::Condvar::new(),
            prints: Prints::default(),
            events: Mutex::new(Events::default()),
        });
        let loader = BzlLoader::with_provider(Box::new(Provider(Arc::downgrade(&inner))), true);
        let _ = inner.loader.set(loader);
        inner.note_repo_rules();
        Ok(Repos { inner })
    }

    /// Run every extension of the graph, in the order it is first used.
    /// `print` gets what they print.
    pub fn run_extensions(&mut self, print: Option<&dyn PrintHandler>) -> Result<(), FetchError> {
        let mut result = Ok(());
        for at in 0..self.inner.extensions.len() {
            result = self.inner.ensure_ran(at);
            if result.is_err() {
                break;
            }
        }
        self.inner.prints.hand_on(print);
        result
    }

    /// What the root module's `use_repo`s name, and the repository each is.
    pub fn imports(&self) -> Vec<(String, String)> {
        let inner = &self.inner;
        let root = &inner.resolution.root;
        let state = inner.state.lock().unwrap();
        let mapping = inner
            .resolution
            .repo_mappings()
            .into_iter()
            .find(|(repo, _)| repo.is_empty())
            .map(|(_, rows)| rows)
            .unwrap_or_default();
        drop(state);
        let mut found = Vec::new();
        for extension in &inner.extensions {
            for (key, index) in &extension.usages {
                if !key.is_root() {
                    continue;
                }
                for (local, _) in &root.extension_usages[*index].imports {
                    if let Some((_, canonical)) = mapping.iter().find(|(n, _)| n == local) {
                        found.push((local.clone(), canonical.clone()));
                    }
                }
            }
        }
        found
    }

    /// The canonical name of the repo the main repository calls `apparent` (what
    /// `@apparent` means there), if it calls one that.
    pub fn main_repo_canonical(&self, apparent: &str) -> Option<String> {
        self.inner
            .state
            .lock()
            .unwrap()
            .mappings
            .find_apparent("", apparent)
    }

    /// `register_toolchains` patterns, with the repo of the module that wrote each.
    pub fn registered_toolchains(&self) -> Vec<(String, String)> {
        self.inner.resolution.registered_toolchains()
    }

    /// `register_execution_platforms` patterns, likewise.
    pub fn registered_execution_platforms(&self) -> Vec<(String, String)> {
        self.inner.resolution.registered_execution_platforms()
    }

    /// The canonical name of the repository of the selected module `name`.
    pub fn module_repo(&self, name: &str) -> Option<String> {
        let resolution = &self.inner.resolution;
        resolution
            .selection
            .keys()
            .find(|key| key.name == name && !key.is_root())
            .map(|key| resolution.canonical_name_of(key))
    }

    /// Every repository a fetch of everything makes, in the order modules and
    /// extensions come: the selected modules' (not the main repository nor
    /// `bazel_tools`, which is served from the output base), then what the
    /// extensions that have run generated.
    pub fn all_repos(&self) -> Vec<String> {
        let inner = &self.inner;
        let mut repos: Vec<String> = inner
            .resolution
            .selection
            .keys()
            .filter(|key| !key.is_root() && key.name != "bazel_tools")
            .map(|key| inner.resolution.canonical_name_of(key))
            .collect();
        repos.extend(inner.state.lock().unwrap().generated.keys().cloned());
        repos
    }

    /// The warnings there were so far, each as Bazel words it after `WARNING: `.
    pub fn warnings(&self) -> Vec<String> {
        self.inner.state.lock().unwrap().warnings.clone()
    }

    /// The `facts` the extensions that ran kept: an extension id and what it kept.
    pub fn locked_facts(&self) -> Vec<(String, Json)> {
        self.inner.state.lock().unwrap().facts.clone()
    }

    /// The extension results the lockfile already has. An extension whose
    /// implementation, usages and recorded inputs are as they were is not run
    /// again; its repositories are the ones the lockfile names.
    pub fn set_previous_extensions(&self, previous: Vec<LockedExtension>) {
        self.inner.state.lock().unwrap().previous = previous;
    }

    /// What the extensions that have run give `MODULE.bazel.lock`.
    pub fn locked_extensions(&self) -> Vec<LockedExtension> {
        self.inner.state.lock().unwrap().locked.clone()
    }

    /// The canonical names of the repositories extensions generated.
    pub fn generated(&self) -> impl Iterator<Item = String> {
        let names: Vec<String> = self
            .inner
            .state
            .lock()
            .unwrap()
            .generated
            .iter()
            .filter(|(_, g)| !g.repo.rule.is_empty())
            .map(|(name, _)| name.clone())
            .collect();
        names.into_iter()
    }

    /// Make the repository `name` (a canonical name), running its rule, and
    /// return its directory.
    pub fn fetch(
        &self,
        name: &str,
        print: Option<&dyn PrintHandler>,
    ) -> Result<PathBuf, FetchError> {
        let inner = &self.inner;
        let result = (|| {
            if !inner.is_repo(name)
                && let Some(at) = inner.extension_of_repo(name)
            {
                inner.ensure_ran(at)?;
            }
            inner.make(name)
        })();
        inner.prints.hand_on(print);
        result?;
        Ok(inner.options.output_base.join("external").join(name))
    }

    /// The extension that generated `name`, `@@//:ext.bzl%ext`.
    pub fn extension_of(&self, name: &str) -> Option<String> {
        let state = self.inner.state.lock().unwrap();
        state.generated.get(name).map(|g| g.extension.clone())
    }

    /// Hand `print` what BUILD files, extensions and rules have printed since
    /// the last call.
    pub fn flush_prints(&self, print: &dyn PrintHandler) {
        self.inner.prints.hand_on(Some(print));
    }

    /// Where the repositories are made, under `external`.
    pub fn output_base(&self) -> &Path {
        &self.inner.options.output_base
    }

    /// The directory of the main repository.
    pub fn workspace_root(&self) -> &Path {
        &self.inner.options.workspace_root
    }

    /// The loader the repositories are read through.
    pub fn loader(&self) -> &BzlLoader {
        self.inner.loader()
    }
}

use fjfj_loading::Purpose;

impl fjfj_loading::PackageSource for Repos {
    fn lookup(&self, repo: &str) -> Result<Arc<PackageLookup>, String> {
        match self.inner.lookup(repo) {
            Ok(Some(lookup)) => Ok(lookup),
            Ok(None) => Err(format!("Repository '@@{repo}' is not defined")),
            Err(e) => Err(e.message),
        }
    }

    fn package(
        &self,
        repo: &str,
        package: &str,
    ) -> Result<Arc<fjfj_graph::package::Package>, String> {
        self.load(repo, package, Purpose::Package)
    }

    fn package_for(
        &self,
        repo: &str,
        package: &str,
        purpose: Purpose,
    ) -> Result<Arc<fjfj_graph::package::Package>, String> {
        self.load(repo, package, purpose)
    }
}

impl Repos {
    /// `package` loaded for `purpose`, which decides the events a failure
    /// is followed by.
    fn load(
        &self,
        repo: &str,
        package: &str,
        purpose: Purpose,
    ) -> Result<Arc<fjfj_graph::package::Package>, String> {
        self.loader()
            .load_package(repo, package)
            .map(|loaded| {
                let mut prints = self.inner.prints.0.lock().unwrap();
                prints.extend(self.loader().take_prints());
                if self
                    .inner
                    .prints
                    .1
                    .lock()
                    .unwrap()
                    .insert((repo.to_owned(), package.to_owned()))
                {
                    prints.extend(loaded.printed);
                }
                Arc::new(loaded.package)
            })
            .map_err(|e| self.package_error(repo, package, e, purpose))
    }

    /// What Bazel says of a package whose BUILD file failed: the events go to
    /// the console (see [`Repos::take_events`]), and the message is the
    /// error of the package.
    fn package_error(
        &self,
        repo: &str,
        package: &str,
        error: fjfj_starlark::BuildFileError,
        purpose: Purpose,
    ) -> String {
        use fjfj_starlark::BuildFileError;
        let name = if repo.is_empty() {
            package.to_owned()
        } else {
            format!("@@{repo}//{package}")
        };
        let mut events = self.inner.events.lock().unwrap();
        // What the files printed before the error comes first, as Bazel
        // shows it, and once for the package.
        self.loader().said_prints();
        events.extend(self.loader().take_events());
        let mut debug = |printed: &[String]| {
            if self
                .inner
                .prints
                .1
                .lock()
                .unwrap()
                .insert((repo.to_owned(), package.to_owned()))
            {
                for text in printed {
                    events
                        .queue
                        .push(fjfj_starlark::debug_line_with(text, &|name| {
                            self.loader().path_of("", name)
                        }));
                }
            }
        };
        match &error {
            BuildFileError::Eval(_, printed) | BuildFileError::Package { printed, .. } => {
                debug(printed)
            }
            _ => debug(&[]),
        }
        let contains_errors = |events: &mut Events, first: &str| {
            // The first event again, without the place it was at.
            let message = first
                .split_once(": ")
                .filter(|(place, _)| {
                    place
                        .rsplit(':')
                        .next()
                        .is_some_and(|c| c.parse::<u32>().is_ok())
                })
                .map_or(first, |(_, message)| message);
            if purpose == Purpose::Tree {
                events.push("package contains errors: ".to_owned());
            }
            if purpose != Purpose::Target {
                events.push(format!("package contains errors: {name}: {message}"));
            }
            format!("error loading package '{name}': Package '{package}' contains errors")
        };
        match error {
            BuildFileError::Absent(message) => message,
            BuildFileError::Load(reason) => {
                format!("error loading package '{name}': {reason}")
            }
            BuildFileError::Eval(text, _) => {
                let text = format!("{text:#}");
                events.push(text.clone());
                contains_errors(&mut events, &text)
            }
            BuildFileError::Package {
                events: reported, ..
            } => {
                let first = reported.first().cloned().unwrap_or_default();
                events.extend(reported);
                contains_errors(&mut events, &first)
            }
        }
    }

    /// The errors packages loaded so far had, each to be shown as an
    /// `ERROR:` line, in the order they happened. A `DEBUG: ` one is what a
    /// file printed before the error after it, and is shown as it is.
    pub fn take_events(&self) -> Vec<String> {
        let mut events = self.inner.events.lock().unwrap();
        events.extend(self.loader().take_events());
        std::mem::take(&mut events.queue)
    }
}

impl fjfj_starlark::RuleSource for Repos {
    fn module(&self, bzl: &Label) -> Result<starlark::environment::FrozenModule, String> {
        self.loader().module_of(bzl)
    }

    fn mappings(&self) -> Arc<RepoMappings> {
        self.inner.state.lock().unwrap().mappings.clone()
    }
}

impl Inner {
    fn loader(&self) -> &BzlLoader {
        self.loader.get().expect("set when made")
    }

    fn load(&self, label: &Label) -> Result<starlark::environment::FrozenModule, FetchError> {
        self.loader()
            .module_of(label)
            .map_err(|message| FetchError { message })
    }

    fn mappings(&self) -> Arc<RepoMappings> {
        self.state.lock().unwrap().mappings.clone()
    }

    fn env(
        self: &Arc<Self>,
        name: &str,
        original: &str,
        output: PathBuf,
        attrs: Vec<(String, RepoAttr)>,
    ) -> RepoEnv {
        let weak = Arc::downgrade(self);
        let own = name.to_owned();
        let here = output.clone();
        RepoEnv {
            name: name.to_owned(),
            original_name: original.to_owned(),
            output,
            workspace_root: self.options.workspace_root.clone(),
            environ: self.options.environ.clone(),
            labels: Box::new(move |label: &Label| {
                if label.repo == own {
                    return Some(here.join(&label.package).join(&label.name));
                }
                let inner = weak.upgrade()?;
                let lookup = inner.lookup(&label.repo).ok()??;
                Some(lookup.package_dir(&label.package).join(&label.name))
            }),
            attrs,
            downloader: self.options.downloader.clone(),
            repository_cache: self.options.repository_cache.clone(),
            distdirs: self.options.distdirs.clone(),
            recorded: Default::default(),
        }
    }

    /// The files of the repository `repo`, made if need be.
    fn lookup(self: &Arc<Self>, repo: &str) -> Result<Option<Arc<PackageLookup>>, FetchError> {
        if let Some(lookup) = self.state.lock().unwrap().lookups.get(repo) {
            return Ok(Some(lookup.clone()));
        }
        if !self.is_repo(repo) {
            // An extension's repos are known once it has run.
            let Some(at) = self.extension_of_repo(repo) else {
                return Ok(None);
            };
            self.ensure_ran(at)?;
            if !self.state.lock().unwrap().generated.contains_key(repo) {
                return Ok(None);
            }
        }
        self.make(repo)?;
        Ok(self.state.lock().unwrap().lookups.get(repo).cloned())
    }

    /// Whether `repo` is a repository of a module of the graph, or one that
    /// an extension is already known to generate.
    fn is_repo(&self, repo: &str) -> bool {
        self.resolution
            .selection
            .keys()
            .any(|key| self.resolution.canonical_name_of(key) == repo)
            || self.state.lock().unwrap().generated.contains_key(repo)
    }

    /// The extension whose repositories `repo` would be one of.
    fn extension_of_repo(&self, repo: &str) -> Option<usize> {
        self.extensions
            .iter()
            .enumerate()
            .filter(|(_, e)| repo.starts_with(&e.repo_name("")))
            .max_by_key(|(_, e)| e.repo_name("").len())
            .map(|(at, _)| at)
    }

    /// Make the repository `name`, running its rule, unless it has been made.
    fn make(self: &Arc<Self>, name: &str) -> Result<(), FetchError> {
        let me = std::thread::current().id();
        let mut state = self.state.lock().unwrap();
        loop {
            if state.lookups.contains_key(name) {
                return Ok(());
            }
            match state.making.get(name) {
                // Needed by the very call that is making it.
                Some(maker) if *maker == me => {
                    return failed(format!(
                        "Circular definition of repository '@@{name}': it is needed to make itself"
                    ));
                }
                // Another thread is on it: wait for the outcome.
                Some(_) => state = self.progress.wait(state).unwrap(),
                None => break,
            }
        }
        state.making.insert(name.to_owned(), me);
        drop(state);
        let made = self.make_unguarded(name);
        self.state.lock().unwrap().making.remove(name);
        self.progress.notify_all();
        made
    }

    fn make_unguarded(self: &Arc<Self>, name: &str) -> Result<(), FetchError> {
        let overridden = self.state.lock().unwrap().overridden.get(name).cloned();
        if let Some(target) = overridden {
            return self.link_override(name, &target);
        }
        let known = self.state.lock().unwrap().generated.contains_key(name);
        if !known {
            // A module's own repository, made by the rule its source names.
            let Some((key, _)) = self
                .resolution
                .selection
                .resolved
                .iter()
                .find(|(key, _)| self.resolution.canonical_name_of(key) == name)
            else {
                return failed(format!("no repository named '@@{name}'"));
            };
            let spec = self
                .resolution
                .module_repo_spec(key, &self.options.registries)
                .map_err(|e| FetchError {
                    message: e.to_string(),
                })?;
            let (file, rule) = match spec.rule {
                RepoRule::HttpArchive => ("http.bzl", "http_archive"),
                RepoRule::GitRepository => ("git.bzl", "git_repository"),
                RepoRule::LocalRepository => ("local.bzl", "local_repository"),
            };
            let raw: Vec<(String, TagValue)> = spec
                .attrs
                .iter()
                .map(|(k, v)| (k.clone(), tag_value(v)))
                .collect();
            let generated = Generated {
                repo: GeneratedRepo {
                    name: key.name.clone(),
                    rule: format!("@@bazel_tools//tools/build_defs/repo:{file}%{rule}"),
                    attrs: Vec::new(),
                    location: String::new(),
                },
                raw_attrs: Some(raw),
                extension: String::new(),
            };
            self.state
                .lock()
                .unwrap()
                .generated
                .insert(name.to_owned(), generated);
        }
        let (repo_name, rule_id, raw, given) = {
            let state = self.state.lock().unwrap();
            let g = &state.generated[name];
            (
                g.repo.name.clone(),
                g.repo.rule.clone(),
                g.raw_attrs.clone(),
                g.repo.attrs.clone(),
            )
        };
        let (file, rule) = rule_id.rsplit_once('%').expect("a rule is FILE%NAME");
        let file = file.to_owned();
        let rule = rule.to_owned();
        let module = self.load(&self.parse_label(&file))?;
        let mut attrs = repository_rule_defaults(&module, &rule);
        let given = match raw {
            Some(raw) => {
                let mappings = self.mappings();
                convert_repo_attrs(&module, &rule, &repo_name, &raw, "", &mappings)
                    .map_err(|message| FetchError { message })?
            }
            None => given,
        };
        for (key, value) in &given {
            attrs.retain(|(k, _)| k != key);
            attrs.push((key.clone(), value.clone()));
        }
        let output = self.options.output_base.join("external").join(name);
        // A repository made by an earlier run, from the same rule, attributes and
        // inputs, is not made again.
        let marker = self
            .options
            .output_base
            .join("external")
            .join(format!("{name}.fjfj-marker"));
        let local = repository_rule_is_local(&module, &rule);
        let key = self.marker_key(&rule_id, &file, &repo_name, &attrs);
        if !local
            && key.is_some()
            && output.exists()
            && self.marker_is_current(&marker, key.as_deref().unwrap_or_default())
        {
            return self.finish_repo(name, &output);
        }
        let _ = std::fs::remove_file(&marker);
        // Bazel starts a repository from nothing: what an earlier fetch left (a
        // symlink the rule makes would be "File exists") is deleted first.
        remove_tree(&output);
        let env = self.env(name, &repo_name, output.clone(), attrs);
        let recorder = env.recorded.clone();
        let mappings = self.mappings();
        run_repository_rule(&module, &rule, env, &mappings, Some(&self.prints))
            .map_err(|e| FetchError { message: e.message })?;
        self.finish_repo(name, &output)?;
        if !local && let Some(key) = key {
            self.write_marker(&marker, &key, &recorder.inputs());
        }
        Ok(())
    }

    /// The repository at `output` is there: it has its boundary file and is
    /// known to the lookups.
    fn finish_repo(&self, name: &str, output: &Path) -> Result<(), FetchError> {
        // A repository has a boundary file. One that is a link to a directory of
        // the user's (`local_repository`) is not ours to write one into.
        let has_boundary = ["MODULE.bazel", "REPO.bazel", "WORKSPACE", "WORKSPACE.bazel"]
            .iter()
            .any(|f| output.join(f).exists());
        if !has_boundary {
            let is_link = std::fs::symlink_metadata(output).is_ok_and(|m| m.is_symlink());
            if is_link {
                return failed(format!(
                    "No MODULE.bazel, REPO.bazel, or WORKSPACE file found in {}",
                    output.display()
                ));
            }
            let _ = std::fs::write(output.join("REPO.bazel"), "");
        }
        let lookup = lookup_at(output, &format!("repo '{name}'"))?;
        self.state
            .lock()
            .unwrap()
            .lookups
            .insert(name.to_owned(), Arc::new(lookup));
        Ok(())
    }

    /// What a made repository depends on besides the files it read: the rule
    /// (its `.bzl` files), the attributes, and fjfj's own marker format.
    fn marker_key(
        &self,
        rule_id: &str,
        file: &str,
        repo_name: &str,
        attrs: &[(String, RepoAttr)],
    ) -> Option<String> {
        use sha2::Digest as _;
        let label = self.parse_label(file);
        let digest = self.loader().transitive_digest(&label)?;
        let mut hash = sha2::Sha256::new();
        hash.update(b"fjfj-marker-1\0");
        hash.update(rule_id.as_bytes());
        hash.update(b"\0");
        hash.update(repo_name.as_bytes());
        hash.update(b"\0");
        hash.update(digest);
        hash.update(format!("{attrs:?}").as_bytes());
        Some(hash.finalize().iter().map(|b| format!("{b:02x}")).collect())
    }

    fn marker_is_current(&self, marker: &Path, key: &str) -> bool {
        let Ok(text) = std::fs::read_to_string(marker) else {
            return false;
        };
        let mut lines = text.lines();
        lines.next() == Some("fjfj-marker 1")
            && lines.next() == Some(key)
            && lines.all(|input| self.input_is_current(input))
    }

    /// Note that the repository was made from `key`, reading `inputs`. Nothing
    /// is written if an input cannot be checked again.
    fn write_marker(&self, marker: &Path, key: &str, inputs: &[RecordedInput]) {
        let mut text = format!("fjfj-marker 1\n{key}\n");
        for input in inputs {
            match self.recorded_text(input) {
                Some(line) if !line.contains('\n') && !line.starts_with("DIRENTS:") => {
                    text.push_str(&line);
                    text.push('\n');
                }
                _ => return,
            }
        }
        let _ = std::fs::write(marker, text);
    }

    /// Where a `MODULE.bazel` call of module `key` was, as Bazel says it: a
    /// dependency's file is named by the registry's URL.
    fn located(&self, key: &ModuleKey, location: &str) -> String {
        let module = self
            .resolution
            .selection
            .resolved
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, m)| m);
        match module.and_then(|m| m.registry.as_deref()) {
            Some(url) if !key.is_root() => {
                format!("{url}/modules/{}/{}/{location}", key.name, key.version)
            }
            _ => location.to_owned(),
        }
    }

    /// Make the repository `name` a link to the directory `target`.
    fn link_override(&self, name: &str, target: &Path) -> Result<(), FetchError> {
        if !target.is_dir() {
            return failed(format!(
                "The repository's path is \"{name}\" (absolute: \"{}\") but it does not exist \
                 or is not a directory.",
                target.display()
            ));
        }
        let output = self.options.output_base.join("external").join(name);
        remove_tree(&output);
        if let Some(parent) = output.parent() {
            std::fs::create_dir_all(parent).map_err(|e| FetchError {
                message: e.to_string(),
            })?;
        }
        std::os::unix::fs::symlink(target, &output).map_err(|e| FetchError {
            message: format!("cannot link {}: {e}", output.display()),
        })?;
        let has_boundary = ["MODULE.bazel", "REPO.bazel", "WORKSPACE", "WORKSPACE.bazel"]
            .iter()
            .any(|f| target.join(f).exists());
        if !has_boundary {
            return failed(format!(
                "No MODULE.bazel, REPO.bazel, or WORKSPACE file found in {}",
                target.display()
            ));
        }
        let lookup = lookup_at(&output, &format!("repo '{name}'"))?;
        self.state
            .lock()
            .unwrap()
            .lookups
            .insert(name.to_owned(), Arc::new(lookup));
        Ok(())
    }

    /// A canonical label written `@@repo//pkg:name`.
    fn parse_label(&self, text: &str) -> Label {
        let rest = text.strip_prefix("@@").unwrap_or(text);
        let (repo, rest) = rest.split_once("//").unwrap_or((rest, ""));
        bzl_label(repo, rest)
    }

    /// `use_repo_rule` calls: each is a repository of its own, named
    /// `<module repo>+<rule>+<name>`.
    fn note_repo_rules(&self) {
        let mut state = self.state.lock().unwrap();
        let mut updates = Vec::new();
        for extension in &self.extensions {
            let Some((_, rule_id)) = extension.id.rsplit_once('%') else {
                continue;
            };
            let Some(rule_bzl) = extension.id.strip_prefix("@@") else {
                continue;
            };
            let (label, _) = rule_bzl.rsplit_once('%').unwrap_or((rule_bzl, ""));
            let file = self.parse_label(&format!("@@{label}"));
            let mut names = Vec::new();
            for (key, index) in &extension.usages {
                let module = &self
                    .resolution
                    .selection
                    .resolved
                    .iter()
                    .find(|(k, _)| k == key)
                    .expect("a selected module")
                    .1;
                for tag in &module.extension_usages[*index].tags {
                    let Some((_, fjfj_bzlmod::attrs::AttrValue::String(name))) =
                        tag.attrs.iter().find(|(k, _)| k == "name")
                    else {
                        continue;
                    };
                    let raw: Vec<(String, TagValue)> = tag
                        .attrs
                        .iter()
                        .filter(|(k, _)| k != "name")
                        .map(|(k, v)| (k.clone(), tag_value(v)))
                        .collect();
                    state.generated.insert(
                        extension.repo_name(name),
                        Generated {
                            repo: GeneratedRepo {
                                name: name.clone(),
                                rule: format!("{}%{rule_id}", label_text(&file)),
                                attrs: Vec::new(),
                                location: tag.location.clone(),
                            },
                            extension: String::new(),
                            raw_attrs: Some(raw),
                        },
                    );
                    names.push(name.clone());
                }
            }
            updates.push((extension.clone(), names));
        }
        let mut mappings = (*state.mappings).clone();
        for (extension, names) in updates {
            let rows = self.resolution.extension_repo_mapping(&extension, &names);
            for name in &names {
                mappings.insert(extension.repo_name(name), rows.clone());
            }
        }
        state.mappings = Arc::new(mappings);
    }

    /// What a previous run kept for `extension`.
    fn facts_of(&self, extension: &ExtensionInstance) -> Vec<(String, FactValue)> {
        fn fact(json: &Json) -> FactValue {
            match json {
                Json::Null => FactValue::None,
                Json::Bool(b) => FactValue::Bool(*b),
                Json::Number(n) => n.as_i64().map_or_else(
                    || FactValue::Float(n.as_f64().unwrap_or_default()),
                    FactValue::Int,
                ),
                Json::String(s) => FactValue::String(s.clone()),
                Json::Array(items) => FactValue::List(items.iter().map(fact).collect()),
                Json::Object(items) => {
                    FactValue::Dict(items.iter().map(|(k, v)| (k.clone(), fact(v))).collect())
                }
            }
        }
        let Some(id) = self.resolution.extension_lock_id(extension) else {
            return Vec::new();
        };
        match self.options.facts.iter().find(|(i, _)| *i == id) {
            Some((_, Json::Object(items))) => {
                items.iter().map(|(k, v)| (k.clone(), fact(v))).collect()
            }
            _ => Vec::new(),
        }
    }

    /// What `extension_metadata()` said against what the root module imports: an
    /// error if it named a repository the extension does not generate, and the
    /// warning (as it is worded after `WARNING: `) for imports that differ.
    fn check_metadata(
        &self,
        extension: &ExtensionInstance,
        made: &fjfj_starlark::ExtensionOutput,
        name: &str,
        location: &str,
    ) -> Result<Option<String>, FetchError> {
        let Some(meta) = &made.metadata else {
            return Ok(None);
        };
        let resolved = &self.resolution.selection.resolved;
        let root = resolved.iter().find(|(k, _)| k.is_root()).map(|(_, m)| m);
        let (mut regular_imports, mut dev_imports): (Vec<&str>, Vec<&str>) =
            (Vec::new(), Vec::new());
        let (mut has_regular, mut has_dev) = (false, false);
        let mut first = None;
        if let Some(root) = root {
            for (key, index) in &extension.usages {
                if !key.is_root() {
                    continue;
                }
                let usage = &root.extension_usages[*index];
                first.get_or_insert((usage, root));
                let into = if usage.dev_dependency {
                    has_dev = true;
                    &mut dev_imports
                } else {
                    has_regular = true;
                    &mut regular_imports
                };
                into.extend(usage.imports.iter().map(|(_, exported)| exported.as_str()));
            }
        }
        // What the root module imports can only be wrong if it uses the extension.
        if first.is_none() {
            return Ok(None);
        }
        let generated: Vec<&str> = made.repos.iter().map(|r| r.name.as_str()).collect();
        fn named<'a>(deps: &'a MetaDeps, generated: &[&'a str]) -> Vec<&'a str> {
            match deps {
                MetaDeps::List(list) => list.iter().map(String::as_str).collect(),
                MetaDeps::All => generated.to_vec(),
                MetaDeps::Unset => Vec::new(),
            }
        }
        let (direct, dev) = (
            named(&meta.direct, &generated),
            named(&meta.dev, &generated),
        );
        if !direct.is_empty() && !has_regular {
            return failed(
                "root_module_direct_deps must be empty if the root module contains no usages with \
                 dev_dependency = False",
            );
        }
        if !dev.is_empty() && !has_dev {
            return failed(
                "root_module_direct_dev_deps must be empty if the root module contains no usages \
                 with dev_dependency = True",
            );
        }
        for (what, list, deps) in [
            ("root_module_direct_deps", &direct, &meta.direct),
            ("root_module_direct_dev_deps", &dev, &meta.dev),
        ] {
            if matches!(deps, MetaDeps::List(_)) {
                let missing: Vec<&str> = list
                    .iter()
                    .copied()
                    .filter(|n| !generated.contains(n))
                    .collect();
                if !missing.is_empty() {
                    return failed(format!(
                        "{what} contained the following repositories not generated by the \
                         extension: {}",
                        missing.join(", ")
                    ));
                }
            }
        }
        if meta.direct == MetaDeps::Unset && meta.dev == MetaDeps::Unset {
            return Ok(None);
        }
        let in_any = |n: &&str| direct.contains(n) || dev.contains(n);
        let sorted = |mut v: Vec<&str>| {
            v.sort_unstable();
            v.dedup();
            v.join(", ")
        };
        let mut sections = String::new();
        let mut section = |title: &str, names: Vec<&str>| {
            if !names.is_empty() {
                sections.push_str(&format!("{title}:\n    {}\n\n", sorted(names)));
            }
        };
        section(
            "Not imported, but reported as direct dependencies by the extension (may cause the \
             build to fail)",
            direct
                .iter()
                .copied()
                .filter(|n| !regular_imports.contains(n) && !dev_imports.contains(n))
                .collect(),
        );
        section(
            "Imported as a regular dependency, but reported as a dev dependency by the extension \
             (may cause the build to fail when used by other modules)",
            regular_imports
                .iter()
                .copied()
                .filter(|n| dev.contains(n))
                .collect(),
        );
        section(
            "Imported as a dev dependency, but reported as a regular dependency by the extension \
             (may cause the build to fail when used by other modules)",
            dev_imports
                .iter()
                .copied()
                .filter(|n| direct.contains(n))
                .collect(),
        );
        section(
            "Imported, but reported as indirect dependencies by the extension",
            regular_imports
                .iter()
                .chain(dev_imports.iter())
                .copied()
                .filter(|n| !in_any(n))
                .collect(),
        );
        if sections.is_empty() {
            return Ok(None);
        }
        let Some((usage, root)) = first else {
            return Ok(None);
        };
        Ok(Some(format!(
            "{location}: The module extension {name} defined in {} reported incorrect imports of \
             repositories via use_repo():\n\n{sections}Fix the use_repo calls by running 'bazel \
             mod tidy'.",
            normalized_bzl(&usage.bzl_file, &root.repo_name)
        )))
    }

    /// What the extension's run gives `MODULE.bazel.lock`; nothing for one
    /// that is reproducible.
    fn locked_entry(
        &self,
        extension: &ExtensionInstance,
        file: &Label,
        made: &fjfj_starlark::ExtensionOutput,
    ) -> Option<LockedExtension> {
        if made.reproducible {
            return None;
        }
        let id = self.resolution.extension_lock_id(extension)?;
        let factors = match (made.os_dependent, made.arch_dependent) {
            (false, false) => "general".to_owned(),
            (true, false) => format!("os:{}", os_factor()),
            (false, true) => format!("arch:{}", arch_factor()),
            (true, true) => format!("os:{},arch:{}", os_factor(), arch_factor()),
        };
        let b64 = |bytes: &[u8]| {
            use base64::Engine as _;
            base64::engine::general_purpose::STANDARD.encode(bytes)
        };
        let bzl_digest = self
            .loader()
            .transitive_digest(file)
            .map(|d| b64(&d))
            .unwrap_or_default();
        // The repo names the files looked up as they loaded, sorted, come first;
        // then what the implementation read, in the order it first did.
        let mapped: Vec<(String, String, String)> =
            self.mappings().lookups_under(file).into_iter().collect();
        let recorded: Vec<Json> = mapped
            .iter()
            .map(|(repo, apparent, canonical)| {
                format!("REPO_MAPPING:{repo},{apparent} {canonical}")
            })
            .chain(
                made.recorded
                    .iter()
                    .filter_map(|input| self.recorded_text(input)),
            )
            .fold(Vec::<String>::new(), |mut all, text| {
                if !all.contains(&text) {
                    all.push(text);
                }
                all
            })
            .into_iter()
            .map(Json::String)
            .collect();
        let specs: Vec<(String, Json)> = made
            .repos
            .iter()
            .map(|repo| {
                (
                    repo.name.clone(),
                    Json::Object(vec![
                        ("repoRuleId".to_owned(), Json::String(repo.rule.clone())),
                        (
                            "attributes".to_owned(),
                            Json::Object(
                                repo.attrs
                                    .iter()
                                    .filter_map(|(k, v)| Some((k.clone(), repo_attr_json(v)?)))
                                    .collect(),
                            ),
                        ),
                    ]),
                )
            })
            .collect();
        Some(LockedExtension {
            id,
            factors,
            entry: Json::Object(
                vec![
                    ("bzlTransitiveDigest".to_owned(), Json::String(bzl_digest)),
                    (
                        "usagesDigest".to_owned(),
                        Json::String(self.resolution.extension_usages_digest(extension)),
                    ),
                    ("recordedInputs".to_owned(), Json::Array(recorded)),
                    ("generatedRepoSpecs".to_owned(), Json::Object(specs)),
                ]
                .into_iter()
                .chain(
                    made.metadata
                        .as_ref()
                        .and_then(metadata_json)
                        .map(|m| ("moduleExtensionMetadata".to_owned(), m)),
                )
                .collect(),
            ),
        })
    }

    /// The lockfile's result for `extension`, if the implementation, the usages
    /// and everything the run read are as they were.
    fn locked_hit(&self, extension: &ExtensionInstance, file: &Label) -> Option<LockedHit> {
        let id = self.resolution.extension_lock_id(extension)?;
        let previous = self.state.lock().unwrap().previous.clone();
        let here = |factors: &str| {
            factors == "general"
                || factors == format!("os:{}", os_factor())
                || factors == format!("arch:{}", arch_factor())
                || factors == format!("os:{},arch:{}", os_factor(), arch_factor())
        };
        let candidates: Vec<LockedExtension> = previous
            .into_iter()
            .filter(|p| p.id == id && here(&p.factors))
            .collect();
        if candidates.is_empty() {
            tracing::debug!(id, "no locked result for the extension");
            return None;
        }
        let b64 = |bytes: &[u8]| {
            use base64::Engine as _;
            base64::engine::general_purpose::STANDARD.encode(bytes)
        };
        let Some(bzl_digest) = self.loader().transitive_digest(file).map(|d| b64(&d)) else {
            tracing::debug!(id, "the extension's .bzl digest is not known");
            return None;
        };
        let usages = self.resolution.extension_usages_digest(extension);
        candidates.into_iter().find(|candidate| {
            let Json::Object(fields) = &candidate.entry else {
                return false;
            };
            let field = |name: &str| fields.iter().find(|(k, _)| k == name).map(|(_, v)| v);
            if !matches!(field("bzlTransitiveDigest"), Some(Json::String(d)) if *d == bzl_digest) {
                tracing::debug!(id, "the extension's .bzl files changed");
                return false;
            }
            if !matches!(field("usagesDigest"), Some(Json::String(d)) if *d == usages) {
                tracing::debug!(id, "the extension's usages changed");
                return false;
            }
            let Some(Json::Array(inputs)) = field("recordedInputs") else {
                return false;
            };
            for input in inputs {
                if !matches!(input, Json::String(t) if self.input_is_current(t)) {
                    tracing::debug!(id, ?input, "an input of the extension changed");
                    return false;
                }
            }
            true
        })
        .map(|entry| LockedHit { entry })
    }

    /// Whether what `recordedInputs` noted is still so.
    fn input_is_current(&self, text: &str) -> bool {
        let file_path = |written: &str| -> Option<PathBuf> {
            let rest = written.strip_prefix("@@")?;
            let (repo, path) = rest.split_once("//")?;
            Some(if repo.is_empty() {
                self.options.workspace_root.join(path)
            } else {
                self.options
                    .output_base
                    .join("external")
                    .join(repo)
                    .join(path)
            })
        };
        if let Some(rest) = text.strip_prefix("REPO_MAPPING:") {
            let Some((head, canonical)) = rest.split_once(' ') else {
                return false;
            };
            let Some((repo, apparent)) = head.split_once(',') else {
                return false;
            };
            let now = self
                .mappings()
                .find_apparent(repo, apparent)
                .unwrap_or_else(|| "\\0".to_owned());
            return now == canonical;
        }
        if let Some(rest) = text.strip_prefix("ENV:") {
            let Some((name, value)) = rest.split_once(' ') else {
                return false;
            };
            let recorded = if value == "\\0" {
                None
            } else {
                Some(
                    value
                        .replace("\\s", " ")
                        .replace("\\n", "\n")
                        .replace("\\\\", "\\"),
                )
            };
            return self.options.environ.get(name) == recorded.as_ref();
        }
        if let Some(rest) = text.strip_prefix("FILE:") {
            let Some((written, hash)) = rest.rsplit_once(' ') else {
                return false;
            };
            let Some(path) = file_path(written) else {
                return false;
            };
            return match std::fs::read(&path) {
                Ok(bytes) => {
                    use sha2::Digest as _;
                    sha2::Sha256::digest(&bytes)
                        .iter()
                        .map(|b| format!("{b:02x}"))
                        .collect::<String>()
                        == hash
                }
                Err(_) => false,
            };
        }
        // Anything else (a directory's names) is not checked here: run again.
        false
    }

    /// `recordedInputs` text for what an extension read: `ENV:`, `FILE:` and
    /// `DIRENTS:`, the paths as `@@repo//path` (and none for a path that is in
    /// no repository).
    fn recorded_text(&self, input: &RecordedInput) -> Option<String> {
        let repo_path = |path: &Path| -> Option<String> {
            if let Ok(rest) = path.strip_prefix(&self.options.workspace_root) {
                return Some(format!("@@//{}", rest.display()));
            }
            let external = self.options.output_base.join("external");
            let rest = path.strip_prefix(&external).ok()?;
            let mut parts = rest.components();
            let repo = parts.next()?.as_os_str().to_string_lossy().into_owned();
            let rest: PathBuf = parts.collect();
            Some(format!("@@{repo}//{}", rest.display()))
        };
        match input {
            RecordedInput::RepoMapping {
                repo,
                apparent,
                canonical,
            } => Some(format!("REPO_MAPPING:{repo},{apparent} {canonical}")),
            RecordedInput::Env { name, value } => {
                let value = match value {
                    None => "\\0".to_owned(),
                    Some(v) => v
                        .replace('\\', "\\\\")
                        .replace(' ', "\\s")
                        .replace('\n', "\\n"),
                };
                Some(format!("ENV:{name} {value}"))
            }
            RecordedInput::File { path, sha256 } => {
                Some(format!("FILE:{} {sha256}", repo_path(path)?))
            }
            RecordedInput::Dirents { path, sha256 } => {
                Some(format!("DIRENTS:{} {sha256}", repo_path(path)?))
            }
        }
    }

    /// Run extension `at` if it has not been, over every usage of it.
    fn ensure_ran(self: &Arc<Self>, at: usize) -> Result<(), FetchError> {
        let extension = &self.extensions[at];
        let me = std::thread::current().id();
        {
            let mut state = self.state.lock().unwrap();
            loop {
                if state.ran.contains(&at) {
                    return Ok(());
                }
                match state.running.get(&at) {
                    Some(runner) if *runner == me => {
                        return failed(format!(
                            "Circular definition of module extension {}: it is needed to run itself",
                            extension.id
                        ));
                    }
                    Some(_) => state = self.progress.wait(state).unwrap(),
                    None => break,
                }
            }
            state.running.insert(at, me);
        }
        let result = self.run_extension(at);
        let mut state = self.state.lock().unwrap();
        state.running.remove(&at);
        if result.is_ok() {
            state.ran.insert(at);
        }
        drop(state);
        self.progress.notify_all();
        result
    }

    fn run_extension(self: &Arc<Self>, at: usize) -> Result<(), FetchError> {
        let extension = &self.extensions[at];
        let resolved = &self.resolution.selection.resolved;
        let module_of = |key: &ModuleKey| &resolved.iter().find(|(k, _)| k == key).unwrap().1;
        // A `use_repo_rule`'s repositories are noted already; what is left is
        // to see the rule is there.
        if let Some(label) = extension.id.strip_prefix("@@") {
            let (label, rule) = label.rsplit_once('%').expect("an id is FILE%NAME");
            let (first_key, first_index) = &extension.usages[0];
            let usage = &module_of(first_key).extension_usages[*first_index];
            let written = usage
                .extension_name
                .split_once(' ')
                .map_or(usage.extension_name.as_str(), |(bzl, _)| bzl);
            let at = usage
                .tags
                .first()
                .map(|t| t.location.clone())
                .unwrap_or_default();
            let module = self.load(&self.parse_label(&format!("@@{label}")))?;
            if !has_repository_rule(&module, rule) {
                return failed(format!(
                    "{written} does not export a repository_rule called {rule}, yet its use is \
                     requested at {at}"
                ));
            }
            return Ok(());
        }
        let (rest, name) = extension.id.rsplit_once('%').expect("an id is FILE%NAME");
        let file = bzl_label(&extension.bzl_repo, rest);
        let extension_id = format!("{}%{name}", label_text(&file));
        let (first_key, first_index) = &extension.usages[0];
        let location = self.located(
            first_key,
            &module_of(first_key).extension_usages[*first_index].location,
        );
        let written = &module_of(first_key).extension_usages[*first_index].bzl_file;
        let module = self.load(&file).map_err(|e| FetchError {
            message: format!(
                "Error loading '{written}' for module extensions, requested by {location}: {}: {}",
                e.message, e.message
            ),
        })?;
        if !has_module_extension(&module, name) {
            return failed(format!(
                "{written} does not export a module extension called {name}, yet its use is \
                 requested at {location}"
            ));
        }
        if let Some(hit) = self.locked_hit(extension, &file) {
            let repos = hit.repos();
            let names: Vec<String> = repos.iter().map(|r| r.name.clone()).collect();
            for (key, index) in &extension.usages {
                let usage = &module_of(key).extension_usages[*index];
                for (local, exported) in &usage.imports {
                    if !names.contains(exported) {
                        return failed(format!(
                            "module extension {extension_id} does not generate repository \
                             \"{exported}\", yet it is imported as \"{local}\" in the usage at {}",
                            self.located(key, &usage.location)
                        ));
                    }
                }
            }
            let rows = self.resolution.extension_repo_mapping(extension, &names);
            let mut state = self.state.lock().unwrap();
            state.locked.push(hit.entry);
            let mut mappings = (*state.mappings).clone();
            for repo in repos {
                let canonical = extension.repo_name(&repo.name);
                mappings.insert(canonical.clone(), rows.clone());
                state.generated.insert(
                    canonical,
                    Generated {
                        repo,
                        extension: extension_id.clone(),
                        raw_attrs: None,
                    },
                );
            }
            state.mappings = Arc::new(mappings);
            return Ok(());
        }
        // One entry per module that uses it, the root first: its usages'
        // tags in the order written.
        let mut uses: Vec<(ModuleUse, bool)> = Vec::new();
        for (key, index) in &extension.usages {
            let owner = module_of(key);
            let usage = &owner.extension_usages[*index];
            let entry = match uses.iter().position(|(m, _)| m.name == owner.name) {
                Some(at) => at,
                None => {
                    uses.push((
                        ModuleUse {
                            name: owner.name.clone(),
                            version: owner.version.to_string(),
                            is_root: key.is_root(),
                            repo: self.resolution.canonical_name_of(key),
                            tags: Vec::new(),
                        },
                        false,
                    ));
                    uses.len() - 1
                }
            };
            uses[entry].0.tags.extend(usage.tags.iter().map(|t| {
                TagUse {
                    class: t.tag_class.clone(),
                    attrs: t
                        .attrs
                        .iter()
                        .map(|(k, v)| (k.clone(), tag_value(v)))
                        .collect(),
                    dev_dependency: t.dev_dependency,
                    location: t.location.clone(),
                }
            }));
            if key.is_root() && !usage.dev_dependency {
                uses[entry].1 = true;
            }
        }
        let root_has_non_dev_dependency = uses.iter().any(|(_, non_dev)| *non_dev);
        let input = ExtensionInput {
            modules: uses.into_iter().map(|(m, _)| m).collect(),
            root_has_non_dev_dependency,
            facts: self.facts_of(extension),
        };
        let prefix = extension.repo_name("");
        let prefix = prefix.trim_end_matches('+').to_owned();
        // Each run starts in an empty directory, as in Bazel: what an earlier
        // run left (or an older fjfj wrote) must not be read as this one's.
        let work = self.options.output_base.join("modextwd").join(&prefix);
        let _ = std::fs::remove_dir_all(&work);
        let env = self.env(&prefix, name, work, Vec::new());
        let mappings = self.mappings();
        let made = run_module_extension(
            &module,
            name,
            &extension_id,
            input,
            env,
            &mappings,
            Some(&self.prints),
        )
        .map_err(|e| FetchError { message: e.message })?;
        // What each module imported has to exist, unless the root replaced it.
        let replaced: Vec<&str> = module_of(&ModuleKey::root())
            .extension_usages
            .iter()
            .enumerate()
            .filter(|(i, _)| extension.usages.iter().any(|(k, j)| k.is_root() && j == i))
            .flat_map(|(_, u)| u.repo_overrides.iter())
            .map(|o| o.overridden_repo_name.as_str())
            .collect();
        for (key, index) in &extension.usages {
            let usage = &module_of(key).extension_usages[*index];
            for (local, exported) in &usage.imports {
                if !made.repos.iter().any(|r| &r.name == exported)
                    && !replaced.contains(&exported.as_str())
                {
                    return failed(format!(
                        "module extension {extension_id} does not generate repository \
                         \"{exported}\", yet it is imported as \"{local}\" in the usage at {}",
                        self.located(key, &usage.location)
                    ));
                }
            }
        }
        let names: Vec<String> = made.repos.iter().map(|r| r.name.clone()).collect();
        let rows = self.resolution.extension_repo_mapping(extension, &names);
        let warning = self.check_metadata(extension, &made, name, &location)?;
        let locked = self.locked_entry(extension, &file, &made);
        let mut state = self.state.lock().unwrap();
        state.warnings.extend(warning);
        if let (Some(entry), Some(meta)) = (&locked, &made.metadata)
            && !meta.facts.is_empty()
        {
            state
                .facts
                .push((entry.id.clone(), facts_json(&meta.facts)));
        }
        state.locked.extend(locked);
        let mut mappings = (*state.mappings).clone();
        for repo in made.repos {
            let canonical = extension.repo_name(&repo.name);
            mappings.insert(canonical.clone(), rows.clone());
            state.generated.insert(
                canonical,
                Generated {
                    repo,
                    extension: extension_id.clone(),
                    raw_attrs: None,
                },
            );
        }
        state.mappings = Arc::new(mappings);
        Ok(())
    }
}

/// A lockfile entry that is still good, and the repositories it names.
struct LockedHit {
    entry: LockedExtension,
}

impl LockedHit {
    /// The repositories of `generatedRepoSpecs`.
    fn repos(&self) -> Vec<fjfj_starlark::GeneratedRepo> {
        let Json::Object(fields) = &self.entry.entry else {
            return Vec::new();
        };
        let Some((_, Json::Object(specs))) = fields.iter().find(|(k, _)| k == "generatedRepoSpecs")
        else {
            return Vec::new();
        };
        specs
            .iter()
            .filter_map(|(name, spec)| {
                let Json::Object(spec) = spec else {
                    return None;
                };
                let rule = match spec.iter().find(|(k, _)| k == "repoRuleId") {
                    Some((_, Json::String(rule))) => rule.clone(),
                    _ => return None,
                };
                let attrs = match spec.iter().find(|(k, _)| k == "attributes") {
                    Some((_, Json::Object(attrs))) => attrs
                        .iter()
                        .filter_map(|(k, v)| Some((k.clone(), repo_attr_from_json(v)?)))
                        .collect(),
                    _ => Vec::new(),
                };
                Some(fjfj_starlark::GeneratedRepo {
                    name: name.clone(),
                    rule,
                    attrs,
                    location: String::new(),
                })
            })
            .collect()
    }
}

/// The inverse of [`quoted`].
fn unquoted(s: &str) -> String {
    if s.len() > 1 && s.starts_with('\'') && s.ends_with('\'') {
        s[1..s.len() - 1].to_owned()
    } else {
        s.to_owned()
    }
}

fn label_from(text: &str) -> Option<Label> {
    if !text.starts_with("@@") {
        return None;
    }
    Label::parse(
        text,
        fjfj_graph::LabelContext {
            repo: "",
            package: "",
        },
    )
    .ok()
}

/// The inverse of [`repo_attr_json`], as far as the lockfile's text tells:
/// a string that starts with `@@` is a label.
fn repo_attr_from_json(value: &Json) -> Option<RepoAttr> {
    fn string(v: &Json) -> Option<&str> {
        match v {
            Json::String(s) => Some(s.as_str()),
            _ => None,
        }
    }
    Some(match value {
        Json::Null => return None,
        Json::Bool(b) => RepoAttr::Bool(*b),
        Json::Number(n) => RepoAttr::Int(n.as_i64()?),
        Json::String(s) => match label_from(s) {
            Some(label) => RepoAttr::Label(label),
            None => RepoAttr::String(unquoted(s)),
        },
        Json::Array(items) => {
            if items.iter().all(|i| matches!(i, Json::Number(_))) && !items.is_empty() {
                RepoAttr::IntList(
                    items
                        .iter()
                        .filter_map(|i| match i {
                            Json::Number(n) => n.as_i64(),
                            _ => None,
                        })
                        .collect(),
                )
            } else if !items.is_empty()
                && items
                    .iter()
                    .all(|i| string(i).is_some_and(|s| s.starts_with("@@")))
            {
                RepoAttr::LabelList(
                    items
                        .iter()
                        .filter_map(|i| string(i).and_then(label_from))
                        .collect(),
                )
            } else {
                RepoAttr::StringList(
                    items
                        .iter()
                        .filter_map(|i| string(i).map(unquoted))
                        .collect(),
                )
            }
        }
        Json::Object(entries) => {
            let keys_are_labels =
                !entries.is_empty() && entries.iter().all(|(k, _)| k.starts_with("@@"));
            if keys_are_labels {
                RepoAttr::LabelKeyedStringDict(
                    entries
                        .iter()
                        .filter_map(|(k, v)| Some((label_from(k)?, unquoted(string(v)?))))
                        .collect(),
                )
            } else if entries
                .iter()
                .all(|(_, v)| matches!(v, Json::String(s) if !s.starts_with("@@")))
            {
                RepoAttr::StringDict(
                    entries
                        .iter()
                        .filter_map(|(k, v)| Some((unquoted(k), unquoted(string(v)?))))
                        .collect(),
                )
            } else if entries
                .iter()
                .all(|(_, v)| matches!(v, Json::String(s) if s.starts_with("@@")))
            {
                RepoAttr::StringKeyedLabelDict(
                    entries
                        .iter()
                        .filter_map(|(k, v)| Some((unquoted(k), label_from(string(v)?)?)))
                        .collect(),
                )
            } else {
                // Lists as values: of strings, or of labels.
                let all_labels = entries.iter().all(|(_, v)| {
                    matches!(v, Json::Array(items) if items.iter().all(|i| string(i).is_some_and(|s| s.starts_with("@@"))))
                });
                if all_labels {
                    RepoAttr::LabelListDict(
                        entries
                            .iter()
                            .filter_map(|(k, v)| match v {
                                Json::Array(items) => Some((
                                    unquoted(k),
                                    items
                                        .iter()
                                        .filter_map(|i| string(i).and_then(label_from))
                                        .collect(),
                                )),
                                _ => None,
                            })
                            .collect(),
                    )
                } else {
                    RepoAttr::StringListDict(
                        entries
                            .iter()
                            .filter_map(|(k, v)| match v {
                                Json::Array(items) => Some((
                                    unquoted(k),
                                    items
                                        .iter()
                                        .filter_map(|i| string(i).map(unquoted))
                                        .collect(),
                                )),
                                _ => None,
                            })
                            .collect(),
                    )
                }
            }
        }
    })
}

/// `moduleExtensions` of `MODULE.bazel.lock` for the extensions that ran: each
/// extension's entry under its factors, both in sorted order.
pub fn module_extensions_json(entries: &[LockedExtension]) -> Json {
    let mut by_id: BTreeMap<&str, BTreeMap<&str, &Json>> = BTreeMap::new();
    for e in entries {
        by_id.entry(&e.id).or_default().insert(&e.factors, &e.entry);
    }
    Json::Object(
        by_id
            .into_iter()
            .map(|(id, factors)| {
                (
                    id.to_owned(),
                    Json::Object(
                        factors
                            .into_iter()
                            .map(|(f, entry)| (f.to_owned(), entry.clone()))
                            .collect(),
                    ),
                )
            })
            .collect(),
    )
}

/// The `moduleExtensionMetadata` of a lockfile entry: none when the extension
/// said nothing worth keeping.
fn metadata_json(meta: &MetadataOut) -> Option<Json> {
    if meta.direct == MetaDeps::Unset && meta.dev == MetaDeps::Unset && meta.facts.is_empty() {
        return None;
    }
    let names = |deps: &MetaDeps| match deps {
        MetaDeps::List(list) => Some(Json::Array(
            list.iter().cloned().map(Json::String).collect(),
        )),
        _ => None,
    };
    let mut fields = Vec::new();
    let use_all = match (&meta.direct, &meta.dev) {
        (MetaDeps::All, _) => "REGULAR",
        (_, MetaDeps::All) => "DEV",
        _ => "NO",
    };
    if use_all == "NO" {
        if let Some(direct) = names(&meta.direct) {
            fields.push(("explicitRootModuleDirectDeps".to_owned(), direct));
        }
        if let Some(dev) = names(&meta.dev) {
            fields.push(("explicitRootModuleDirectDevDeps".to_owned(), dev));
        }
    }
    fields.push(("useAllRepos".to_owned(), Json::String(use_all.to_owned())));
    fields.push(("reproducible".to_owned(), Json::Bool(meta.reproducible)));
    Some(Json::Object(fields))
}

/// An extension's `facts` as the lockfile keeps them: keys in sorted order,
/// `None` left out of a dict.
fn facts_json(facts: &[(String, FactValue)]) -> Json {
    fn value(v: &FactValue) -> Json {
        match v {
            FactValue::None => Json::Null,
            FactValue::Bool(b) => Json::Bool(*b),
            FactValue::Int(i) => Json::Number((*i).into()),
            FactValue::Float(f) => {
                serde_json::Number::from_f64(*f).map_or(Json::Null, Json::Number)
            }
            FactValue::String(s) => Json::String(s.clone()),
            FactValue::List(items) => Json::Array(items.iter().map(value).collect()),
            FactValue::Dict(items) => dict(items),
        }
    }
    fn dict(items: &[(String, FactValue)]) -> Json {
        let sorted: BTreeMap<&str, &FactValue> = items
            .iter()
            .filter(|(_, v)| !matches!(v, FactValue::None))
            .map(|(k, v)| (k.as_str(), v))
            .collect();
        Json::Object(
            sorted
                .into_iter()
                .map(|(k, v)| (k.to_owned(), value(v)))
                .collect(),
        )
    }
    dict(facts)
}

fn os_factor() -> &'static str {
    match std::env::consts::OS {
        "macos" => "mac os x",
        other => other,
    }
}

fn arch_factor() -> &'static str {
    match std::env::consts::ARCH {
        "x86_64" => "amd64",
        other => other,
    }
}

/// Deletes what is at `path` (a file, a link, or a tree), including the
/// read-only directories an archive leaves, as Bazel's `deleteTree` does.
fn remove_tree(path: &Path) {
    use std::os::unix::fs::PermissionsExt as _;
    fn writable(dir: &Path) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            if entry.file_type().is_ok_and(|t| t.is_dir()) {
                writable(&entry.path());
            }
        }
        let _ = std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o700));
    }
    let Ok(meta) = std::fs::symlink_metadata(path) else {
        return;
    };
    if !meta.is_dir() {
        let _ = std::fs::remove_file(path);
        return;
    }
    if std::fs::remove_dir_all(path).is_err() {
        // A directory without write permission cannot lose its entries: open
        // every one up from the top, then try again. (`read_dir` needs `r-x`.)
        let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700));
        writable(path);
        let _ = std::fs::remove_dir_all(path);
    }
}

/// A string the lockfile reads back as itself: one that would pass for a
/// canonical label (`@@...`) or is already wrapped in `'` is wrapped in `'`
/// (Bazel's `AttributeValuesAdapter`, probed 9.2.0).
pub(crate) fn quoted(s: &str) -> String {
    if s.starts_with("@@") || (s.len() > 1 && s.starts_with('\'') && s.ends_with('\'')) {
        format!("'{s}'")
    } else {
        s.to_owned()
    }
}

/// An attribute of a generated repository as the lockfile writes it (what
/// `AttributeValuesAdapter` does): `None` is left out, a label is its
/// canonical form.
fn repo_attr_json(value: &RepoAttr) -> Option<Json> {
    let text = |s: &str| Json::String(quoted(s));
    let label = |l: &Label| Json::String(label_text(l));
    let strings = |items: &[String]| Json::Array(items.iter().map(|s| text(s)).collect());
    Some(match value {
        RepoAttr::None => return None,
        RepoAttr::Bool(b) => Json::Bool(*b),
        RepoAttr::Int(i) => Json::Number((*i).into()),
        RepoAttr::String(s) => text(s),
        RepoAttr::StringList(items) => strings(items),
        RepoAttr::StringDict(items) => {
            Json::Object(items.iter().map(|(k, v)| (quoted(k), text(v))).collect())
        }
        RepoAttr::StringListDict(items) => {
            Json::Object(items.iter().map(|(k, v)| (quoted(k), strings(v))).collect())
        }
        RepoAttr::IntList(items) => {
            Json::Array(items.iter().map(|i| Json::Number((*i).into())).collect())
        }
        RepoAttr::Label(l) => label(l),
        RepoAttr::LabelList(items) => Json::Array(items.iter().map(label).collect()),
        RepoAttr::StringKeyedLabelDict(items) => {
            Json::Object(items.iter().map(|(k, v)| (quoted(k), label(v))).collect())
        }
        RepoAttr::LabelKeyedStringDict(items) => Json::Object(
            items
                .iter()
                .map(|(k, v)| (label_text(k), text(v)))
                .collect(),
        ),
        RepoAttr::LabelListDict(items) => Json::Object(
            items
                .iter()
                .map(|(k, v)| (quoted(k), Json::Array(v.iter().map(label).collect())))
                .collect(),
        ),
    })
}

fn tag_value(value: &fjfj_bzlmod::attrs::AttrValue) -> TagValue {
    use fjfj_bzlmod::attrs::AttrValue;
    match value {
        AttrValue::None => TagValue::None,
        AttrValue::Bool(b) => TagValue::Bool(*b),
        AttrValue::Int(i) => TagValue::Int(*i),
        AttrValue::String(s) => TagValue::String(s.clone()),
        AttrValue::List(items) => TagValue::List(items.iter().map(tag_value).collect()),
        AttrValue::Dict(items) => TagValue::Dict(
            items
                .iter()
                .map(|(k, v)| (tag_value(k), tag_value(v)))
                .collect(),
        ),
    }
}

/// The top-level symlinks of `root` that lead into `output_base`: the
/// convenience links, whatever `--symlink_prefix` named them.
fn links_into(root: &Path, output_base: &Path) -> Vec<String> {
    let Ok(entries) = std::fs::read_dir(root) else {
        return Vec::new();
    };
    entries
        .flatten()
        .filter(|e| std::fs::read_link(e.path()).is_ok_and(|t| t.starts_with(output_base)))
        .filter_map(|e| e.file_name().into_string().ok())
        .collect()
}
