//! Making repositories: running the module extensions a module graph uses
//! and the repository rules they (and `use_repo_rule`) name, in a directory
//! of the caller's choosing (buildfiji-mum.8.4).
//!
//! This is the driver that joins the module graph (`fjfj-bzlmod`) to the
//! Starlark that runs ([`fjfj_starlark::run_module_extension`],
//! [`fjfj_starlark::run_repository_rule`]). It handles extensions defined in
//! the main repository and used by the root module: the `.bzl` files of any
//! other module need that module's repository fetched first
//! (buildfiji-mum.12), and what several modules' tags do to one extension
//! waits for the same.
//!
//! What Bazel 9.2.0 does, all read off probes of `bazel fetch`:
//!
//! - An extension is run once, over every usage of it, when one of the
//!   repositories it generates is wanted. A repository it generates is named
//!   `<repo of the .bzl>+<extension>+<name>`: `+ext+a` for an extension in
//!   the main repository, `rules_java++toolchains+local_jdk` for one in
//!   `rules_java`.
//! - What the root module imports with `use_repo` must be generated by the
//!   extension: `module extension @@//:ext.bzl%ext does not generate
//!   repository "zzz", yet it is imported as "zzz" in the usage at
//!   MODULE.bazel:2:20`. Imports are checked in order, after the
//!   implementation has run.
//! - An extension's working directory is `modextwd/<repo prefix>` in the
//!   output base, and a generated repository is made in `external/<name>`.

#[cfg(test)]
mod driver_tests;
#[cfg(test)]
mod replay_matrix;
#[cfg(test)]
mod replay_tests;

use fjfj_bzlmod::Module;
use fjfj_graph::{Label, LabelContext};
use fjfj_loading::PackageLookup;
use fjfj_starlark::{
    BzlLoader, ExtensionInput, GeneratedRepo, ModuleUse, RepoAttr, RepoEnv, RepoMappings, TagUse,
    TagValue, convert_repo_attrs, has_module_extension, has_repository_rule,
    repository_rule_defaults, run_module_extension, run_repository_rule,
};
use starlark::PrintHandler;
use starlark::eval::FileLoader;
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};

/// Why a repository could not be made: Bazel's message for it.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{message}")]
pub struct FetchError {
    pub message: String,
}

fn failed<T>(message: impl Into<String>) -> Result<T, FetchError> {
    Err(FetchError {
        message: message.into(),
    })
}

/// What making the repositories of a workspace needs.
pub struct Options {
    /// The main repository's directory.
    pub workspace_root: PathBuf,
    /// Where extensions work (`modextwd`) and repositories are made
    /// (`external`).
    pub output_base: PathBuf,
    /// The client's environment.
    pub environ: BTreeMap<String, String>,
}

/// A repository an extension generated, by the name it is fetched under.
struct Generated {
    repo: GeneratedRepo,
    /// What a `use_repo_rule` call gave, not yet read as the rule's types:
    /// that needs the rule's `.bzl` loaded.
    raw_attrs: Option<Vec<(String, TagValue)>>,
    /// The extension that made it, `@@//:ext.bzl%ext`.
    extension: String,
}

/// The repositories of a workspace.
pub struct Repos {
    options: Options,
    loader: BzlLoader,
    mappings: RepoMappings,
    root: Module,
    /// Repositories extensions generated, by canonical name.
    generated: BTreeMap<String, Generated>,
    /// What the root module imported, as `(name it uses, canonical name)`.
    imports: Vec<(String, String)>,
}

fn label_text(label: &Label) -> String {
    format!("@@{}//{}:{}", label.repo, label.package, label.name)
}

impl Repos {
    /// The repositories of the workspace whose root module is `root`.
    pub fn new(options: Options, root: Module) -> Result<Repos, FetchError> {
        let lookup = PackageLookup::new(&options.workspace_root).map_err(|e| FetchError {
            message: e.to_string(),
        })?;
        let mut rows = vec![
            (String::new(), String::new()),
            (root.repo_name.clone(), String::new()),
        ];
        for dep in &root.deps {
            rows.push((dep.repo_name.clone(), dep.spec.name.clone()));
        }
        rows.push(("bazel_tools".to_owned(), "bazel_tools".to_owned()));
        let mappings = RepoMappings::from_repos([(String::new(), rows)]);
        let loader = BzlLoader::new(
            HashMap::from([(String::new(), lookup)]),
            mappings.clone(),
            true,
        );
        Ok(Repos {
            options,
            loader,
            mappings,
            root,
            generated: BTreeMap::new(),
            imports: Vec::new(),
        })
    }

    /// The `.bzl` file as a label, written in the root module.
    fn label_of(&self, text: &str) -> Result<Label, FetchError> {
        Label::parse_mapped(
            text,
            LabelContext {
                repo: "",
                package: "",
            },
            &mut |apparent| self.mappings.resolve_apparent("", apparent),
        )
        .map_err(|e| FetchError {
            message: e.to_string(),
        })
    }

    fn load(&self, text: &str) -> Result<starlark::environment::FrozenModule, FetchError> {
        let importer = Label {
            repo: String::new(),
            package: String::new(),
            name: "MODULE.bazel".to_owned(),
        };
        self.loader
            .importing(importer)
            .load(text)
            .map_err(|e| FetchError {
                message: e.to_string(),
            })
    }

    fn env(
        &self,
        name: &str,
        original: &str,
        output: PathBuf,
        attrs: Vec<(String, RepoAttr)>,
    ) -> RepoEnv {
        let workspace = self.options.workspace_root.clone();
        RepoEnv {
            name: name.to_owned(),
            original_name: original.to_owned(),
            output,
            workspace_root: self.options.workspace_root.clone(),
            environ: self.options.environ.clone(),
            labels: Box::new(move |label: &Label| {
                label
                    .repo
                    .is_empty()
                    .then(|| workspace.join(&label.package).join(&label.name))
            }),
            attrs,
        }
    }

    /// Run every extension the root module uses, in the order it first uses
    /// them. `print` gets what they print.
    pub fn run_extensions(&mut self, print: Option<&dyn PrintHandler>) -> Result<(), FetchError> {
        // The usages, merged by extension: a module's dev and non-dev uses of
        // one extension are the same extension's input.
        let mut order: Vec<(String, String)> = Vec::new();
        for usage in &self.root.extension_usages {
            let key = (usage.bzl_file.clone(), usage.extension_name.clone());
            if !order.contains(&key) {
                order.push(key);
            }
        }
        for (bzl, name) in order {
            let usages: Vec<_> = self
                .root
                .extension_usages
                .iter()
                .filter(|u| u.bzl_file == bzl && u.extension_name == name)
                .cloned()
                .collect();
            // `use_repo_rule` is an extension of its own, named `<bzl> <rule>`.
            if bzl == fjfj_bzlmod::eval::INNATE_EXTENSION_FILE {
                let (rule_bzl, rule) = name.split_once(' ').unwrap_or((&name, ""));
                let at = usages
                    .iter()
                    .flat_map(|u| u.tags.first())
                    .map(|t| t.location.clone())
                    .next()
                    .unwrap_or_default();
                let file = self.label_of(rule_bzl)?;
                let module = self.load(rule_bzl)?;
                if !has_repository_rule(&module, rule) {
                    return failed(format!(
                        "{rule_bzl} does not export a repository_rule called {rule}, yet its \
                         use is requested at {at}"
                    ));
                }
                self.note_repo_rules(&file, rule, &usages);
                continue;
            }
            let file = self.label_of(&bzl)?;
            let location = usages
                .first()
                .map(|u| u.location.clone())
                .unwrap_or_default();
            let module = self.load(&bzl).map_err(|e| FetchError {
                message: format!(
                    "Error loading '{bzl}' for module extensions, requested by {location}: {}: {}",
                    e.message, e.message
                ),
            })?;
            if !has_module_extension(&module, &name) {
                return failed(format!(
                    "{bzl} does not export a module extension called {name}, yet its use is \
                     requested at {location}"
                ));
            }
            let tags: Vec<TagUse> = usages
                .iter()
                .flat_map(|u| u.tags.iter())
                .map(|t| TagUse {
                    class: t.tag_class.clone(),
                    attrs: t
                        .attrs
                        .iter()
                        .map(|(k, v)| (k.clone(), tag_value(v)))
                        .collect(),
                    dev_dependency: t.dev_dependency,
                    location: t.location.clone(),
                })
                .collect();
            let input = ExtensionInput {
                modules: vec![ModuleUse {
                    name: self.root.name.clone(),
                    version: self.root.version.to_string(),
                    is_root: true,
                    repo: String::new(),
                    tags,
                }],
                root_has_non_dev_dependency: usages.iter().any(|u| !u.dev_dependency),
            };
            let prefix = format!("{}+{name}", file.repo);
            let extension_id = format!("{}%{name}", label_text(&file));
            let env = self.env(
                &prefix,
                &name,
                self.options.output_base.join("modextwd").join(&prefix),
                Vec::new(),
            );
            let made = run_module_extension(
                &module,
                &name,
                &extension_id,
                input,
                env,
                &self.mappings,
                print,
            )
            .map_err(|e| FetchError { message: e.message })?;
            for usage in &usages {
                for (local, exported) in &usage.imports {
                    if !made.repos.iter().any(|r| &r.name == exported) {
                        return failed(format!(
                            "module extension {extension_id} does not generate repository \
                             \"{exported}\", yet it is imported as \"{local}\" in the usage at {}",
                            usage.location
                        ));
                    }
                    self.imports
                        .push((local.clone(), format!("{prefix}+{exported}")));
                }
            }
            for repo in made.repos {
                self.generated.insert(
                    format!("{prefix}+{}", repo.name),
                    Generated {
                        repo,
                        extension: extension_id.clone(),
                        raw_attrs: None,
                    },
                );
            }
        }
        Ok(())
    }

    /// `use_repo_rule` calls: each is a repository of its own, named
    /// `+<rule>+<name>`.
    fn note_repo_rules(
        &mut self,
        file: &Label,
        rule: &str,
        usages: &[fjfj_bzlmod::module::ExtensionUsage],
    ) {
        for usage in usages {
            for tag in &usage.tags {
                let Some((_, fjfj_bzlmod::attrs::AttrValue::String(name))) =
                    tag.attrs.iter().find(|(k, _)| k == "name")
                else {
                    continue;
                };
                let prefix = format!("+{rule}");
                let raw: Vec<(String, TagValue)> = tag
                    .attrs
                    .iter()
                    .filter(|(k, _)| k != "name")
                    .map(|(k, v)| (k.clone(), tag_value(v)))
                    .collect();
                self.generated.insert(
                    format!("{prefix}+{name}"),
                    Generated {
                        repo: GeneratedRepo {
                            name: name.clone(),
                            rule: format!("{}%{rule}", label_text(file)),
                            attrs: Vec::new(),
                            location: tag.location.clone(),
                        },
                        extension: String::new(),
                        raw_attrs: Some(raw),
                    },
                );
                self.imports
                    .push((name.clone(), format!("{prefix}+{name}")));
            }
        }
    }

    /// What the root module's `use_repo`s name, and the repository each is.
    pub fn imports(&self) -> &[(String, String)] {
        &self.imports
    }

    /// The canonical names of the repositories extensions generated.
    pub fn generated(&self) -> impl Iterator<Item = &str> {
        self.generated.keys().map(String::as_str)
    }

    /// Make the repository `name` (a canonical name), running its rule, and
    /// return its directory.
    pub fn fetch(
        &self,
        name: &str,
        print: Option<&dyn PrintHandler>,
    ) -> Result<PathBuf, FetchError> {
        let Some(generated) = self.generated.get(name) else {
            return failed(format!("no repository named '@@{name}'"));
        };
        let (file, rule) = generated
            .repo
            .rule
            .rsplit_once('%')
            .expect("a rule is FILE%NAME");
        let module = self.load(file)?;
        let mut attrs = repository_rule_defaults(&module, rule);
        let given = match &generated.raw_attrs {
            Some(raw) => {
                convert_repo_attrs(&module, rule, &generated.repo.name, raw, "", &self.mappings)
                    .map_err(|message| FetchError { message })?
            }
            None => generated.repo.attrs.clone(),
        };
        for (key, value) in &given {
            attrs.retain(|(k, _)| k != key);
            attrs.push((key.clone(), value.clone()));
        }
        let output = self.options.output_base.join("external").join(name);
        let env = self.env(name, &generated.repo.name, output.clone(), attrs);
        run_repository_rule(&module, rule, env, &self.mappings, print)
            .map_err(|e| FetchError { message: e.message })?;
        let repo_file = output.join("REPO.bazel");
        if !repo_file.exists() {
            let _ = std::fs::write(&repo_file, "");
        }
        Ok(output)
    }

    /// The extension that generated `name`, `@@//:ext.bzl%ext`.
    pub fn extension_of(&self, name: &str) -> Option<&str> {
        self.generated.get(name).map(|g| g.extension.as_str())
    }

    /// The directory of the main repository.
    pub fn workspace_root(&self) -> &Path {
        &self.options.workspace_root
    }

    /// Keep the loader alive for callers that want to share it.
    pub fn loader(&self) -> &BzlLoader {
        &self.loader
    }
}

fn tag_value(value: &fjfj_bzlmod::attrs::AttrValue) -> TagValue {
    use fjfj_bzlmod::attrs::AttrValue;
    match value {
        AttrValue::None => TagValue::None,
        AttrValue::Bool(b) => TagValue::Bool(*b),
        AttrValue::Int(i) => TagValue::Int(*i),
        AttrValue::String(s) => TagValue::String(s.clone()),
        AttrValue::List(items) => TagValue::List(items.iter().map(tag_value).collect()),
        AttrValue::Dict(items) => TagValue::Dict(
            items
                .iter()
                .map(|(k, v)| (tag_value(k), tag_value(v)))
                .collect(),
        ),
    }
}
