//! Generated from Bazel 9.2.0 probes: what `bazel fetch` made of a module extension.

use crate::replay_tests::ExtRow;

pub(crate) const EXT_ROWS: &[ExtRow] = &[
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    for m in mctx.modules:
        for t in m.tags.tag:
            print(t.name, t.value)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"a va"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
    repo(name="a", value="y")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"A repo named a is already generated by this module extension at ext.bzl:6:9"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="b", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"module extension @@//:ext.bzl%ext does not generate repository "a", yet it is imported as "a" in the usage at MODULE.bazel:2:20"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"expected string for attribute 'name', got 'NoneType'"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", bogus="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"in call to 'repo' repo rule with name 'a', unknown attribute 'bogus' provided"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value=1)
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"in call to 'repo' repo rule with name 'a', expected value of type 'string' for attribute 'value', but got 1 (int)"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo("a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"unexpected positional arguments"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name=1, value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"expected string for attribute 'name', got 'int'"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(repo(name="a", value="x"))
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"None"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(type(repo(name="a", value="x")))
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"NoneType"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    x = 1 + "a"
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"unsupported binary operation: int + string"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    fail("boom")
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"boom"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a b", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"invalid user-provided repo name 'a b': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter or a number"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"invalid user-provided repo name '': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter or a number"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "_a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="_a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@_a"#],
        error: Some(
            r#"invalid user-provided repo name '_a': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter or a number"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a.b")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a.b", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a.b"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a.b"#, r#"+ext+a.b"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a.b"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a", "b")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
    repo(name="b", value="y")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@b"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#"b"#, r#"+ext+b"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+b"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x y"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a", "zzz")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"module extension @@//:ext.bzl%ext does not generate repository "zzz", yet it is imported as "zzz" in the usage at MODULE.bazel:2:20"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, mine="a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@mine"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"mine"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'a' cannot be defined by a use_repo() call at MODULE.bazel:4:9 as it is already defined by a use_repo() call at MODULE.bazel:3:9"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext2 = use_extension("//:ext.bzl", "ext")
use_repo(ext2, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'a' cannot be defined by a use_repo() call at MODULE.bazel:5:9 as it is already defined by a use_repo() call at MODULE.bazel:3:9"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext2 = use_extension("//:ext.bzl", "ext")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print("ran")
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"ran"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext2 = use_extension("//:ext.bzl", "ext", dev_dependency=True)
ext2.tag(name="d")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print("ran")
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"ran"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext.tag(name="n1")
ext2 = use_extension("//:ext.bzl", "ext", dev_dependency=True)
ext2.tag(name="d1")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    for m in mctx.modules:
        for t in m.tags.tag:
            print(t.name, mctx.is_dev_dependency(t))
    print(mctx.root_module_has_non_dev_dependency)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"n1 False"#, r#"d1 True"#, r#"True"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext", dev_dependency=True)
use_repo(ext, "a")
ext.tag(name="d1")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    for m in mctx.modules:
        for t in m.tags.tag:
            print(t.name, mctx.is_dev_dependency(t))
    print(mctx.root_module_has_non_dev_dependency)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"d1 True"#, r#"False"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext.tag(name="t1")
ext.tag(name="t2", value="v2")
ext.tag(name="t3")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    for m in mctx.modules:
        for t in m.tags.tag:
            print(t.name, t.value)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"t1 dflt"#, r#"t2 v2"#, r#"t3 dflt"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext.tag(name=1)
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    for m in mctx.modules:
        for t in m.tags.tag:
            print(t.name, t.value)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"in 'tag' tag, expected value of type 'string' for attribute 'name', but got 1 (int)"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext.tag(bogus=1)
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"in 'tag' tag, unknown attribute 'bogus' provided"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext.nothing(name="x")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The module extension defined at ext.bzl:7:23 does not have a tag class named nothing, but its use is attempted at MODULE.bazel:4:12"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext.tag()
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"req": attr.string(mandatory=True)})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"in 'tag' tag, mandatory attribute 'req' isn't being specified"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext.tag()
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    for m in mctx.modules:
        for t in m.tags.tag:
            print(t.req, t.n, t.b, t.l, t.d)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"req": attr.string(), "n": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict()})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#" 0 False [] {}"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
ext.tag()
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(mctx.modules[0].tags.tag)
    print(len(mctx.modules[0].tags.other))
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(), "other": tag_class()})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[
            r#"[<unknown object com.google.devtools.build.lib.bazel.bzlmod.TypeCheckedTag>]"#,
            r#"0"#,
        ],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(mctx.modules[0].tags.nothing)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"unknown tag class nothing"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(mctx.path("."))
    print(mctx.path("x"))
    print(type(mctx.path("x")))
    print(mctx.path("/abs"), mctx.path("../y"))
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[
            r#"<work>/+ext"#,
            r#"<work>/+ext/x"#,
            r#"path"#,
            r#"/abs <work>/y"#,
        ],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    mctx.file("out.txt", "hello")
    print(mctx.read("out.txt"))
    print(mctx.path("out.txt").exists)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"hello"#, r#"True"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    r = mctx.execute(["sh", "-c", "echo hi > f; ls"])
    print(r.stdout)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"f"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(mctx.read(Label("//:f1.txt")))
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
            (r#"f1.txt"#, r#"from ws"#),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"from ws"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    pass
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(mctx.modules[0].name, mctx.modules[0].version)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"probe 1.2"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(repr(mctx.modules[0].name), repr(mctx.modules[0].version))
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#""probe" """#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(repr(mctx.modules[0].name), repr(mctx.modules[0].version))
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#""" """#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    mctx.file("out.txt", "hello", False)
    mctx.file("../esc.txt", "x")
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"Cannot write outside of the repository directory for path <work>/esc.txt"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    mctx.file(Label("//:f1.txt"), "x")
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
            (r#"f1.txt"#, r#"a"#),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"Cannot write outside of the repository directory for path f1.txt"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    x = mctx.modules[0].tags.tag[0]
    print(x.name)
    print(x)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"a"#, r#"'tag' tag at MODULE.bazel:3:8"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(mctx.root_module_has_non_dev_dependency)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"True"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print(len(mctx.modules[0].tags.tag))
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"0"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    print("ran")
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#, r#"@a"#],
        error: None,
        printed: &[r#"ran"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", version="1.2")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a", value="va")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    mctx.file("out.txt", "hello")
    print(mctx.path(".").exists)
    print(mctx.execute(["ls", "-A"]).stdout)
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[r#"True"#, r#"out.txt"#],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
bazel_dep(name="a", version="1.0")
bazel_dep(name="a", version="1.0")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'a' cannot be defined by a bazel_dep at MODULE.bazel:3:10 as it is already defined by a bazel_dep at MODULE.bazel:2:10"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="a")
bazel_dep(name="a", version="1.0")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'a' cannot be defined by a bazel_dep at MODULE.bazel:2:10 as it is already defined as the current module name at MODULE.bazel:1:7"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe", repo_name="b")
bazel_dep(name="x", version="1.0", repo_name="b")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'b' cannot be defined by a bazel_dep at MODULE.bazel:2:10 as it is already defined as the module's own repo name at MODULE.bazel:1:7"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
bazel_dep(name="a", version="1.0", repo_name="r")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "r")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'r' cannot be defined by a use_repo() call at MODULE.bazel:4:9 as it is already defined by a bazel_dep at MODULE.bazel:2:10"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:ext.bzl", "repo")
r(name="x", value="1")
r(name="x", value="2")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'x' cannot be defined by a repo rule at MODULE.bazel:4:2 as it is already defined by a repo rule at MODULE.bazel:3:2"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "x")
r = use_repo_rule("//:ext.bzl", "repo")
r(name="x", value="2")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'x' cannot be defined by a repo rule at MODULE.bazel:5:2 as it is already defined by a use_repo() call at MODULE.bazel:3:9"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
bazel_dep(name="probe", version="1.0")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"The repo name 'probe' cannot be defined by a bazel_dep at MODULE.bazel:2:10 as it is already defined as the current module name at MODULE.bazel:1:7"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "nothing")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"//:ext.bzl does not export a module extension called nothing, yet its use is requested at MODULE.bazel:2:20"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "notext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
notext = 1
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"//:ext.bzl does not export a module extension called notext, yet its use is requested at MODULE.bazel:2:20"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "notext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
def notext(): pass
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"//:ext.bzl does not export a module extension called notext, yet its use is requested at MODULE.bazel:2:20"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:missing.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"Error loading '//:missing.bzl' for module extensions, requested by MODULE.bazel:2:20: cannot load '//:missing.bzl': no such file: cannot load '//:missing.bzl': no such file"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"x = 
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"ext.bzl:1:5: syntax error at 'newline': expected expression"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"fail('load boom')
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"load boom"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name="a", value="x")
ext = module_extension(_impl, tag_classes={"tag": tag_class(attrs={"name": attr.string(), "value": attr.string(default="dflt")})})
y = 1 + 'a'
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"unsupported binary operation: int + string"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
rules = {'r': repository_rule(_repo_impl, attrs={'value': attr.string()})}
def _impl(mctx):
    rules['r'](name='a', value='x')
ext = module_extension(_impl)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"attempting to instantiate a non-exported repository rule"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name='a', value='x')
ext = module_extension(lambda: 1)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"lambda() does not accept positional arguments, but got 1"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl():
    repo(name='a', value='x')
ext = module_extension(_impl)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"_impl() does not accept positional arguments, but got 1"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx, extra):
    repo(name='a', value='x')
ext = module_extension(_impl)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(r#"_impl() missing 1 required positional argument: extra"#),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name='a', value='x')
    return 5
ext = module_extension(_impl)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"expected module extension @@//:ext.bzl%ext to return None or extension_metadata, got int"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name='a', value='x')
ext = module_extension(_impl)
other = module_extension(_impl)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "alias")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name='a', value='x')
ext = module_extension(_impl)
alias = ext
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a"#, r#"+alias+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+alias+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name='a', value='x')
    repo(name='b', value='y')
ext = module_extension(_impl)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "_ext")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
_private = 1
def _impl(mctx):
    repo(name='a', value='x')
_ext = module_extension(_impl)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a"#, r#"+_ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+_ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
ext.tag(name="a")
ext.tag(name="b")
use_repo(ext, "a")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name='a', value='x')
ext = module_extension(_impl, tag_classes={'tag': tag_class(attrs={'name': attr.string()})})
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: None,
        printed: &[],
        mapping: &[
            (r#"a"#, r#"+ext+a"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+ext+a"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"v.txt"#, r#"x x"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
ext = use_extension("//:ext.bzl", "ext")
use_repo(ext, "a")
use_repo(ext, "a2")
"#,
            ),
            (
                r#"ext.bzl"#,
                r#"def _repo_impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("v.txt", ctx.attr.value)
repo = repository_rule(_repo_impl, attrs={"value": attr.string()})
def _impl(mctx):
    repo(name='a', value='x')
ext = module_extension(_impl)
"#,
            ),
        ],
        fetch: &[r#"@a"#],
        error: Some(
            r#"module extension @@//:ext.bzl%ext does not generate repository "a2", yet it is imported as "a2" in the usage at MODULE.bazel:2:20"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r(name="x")
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: None,
        printed: &[r#"attrs ds 7 False [] {}"#],
        mapping: &[
            (r#"x"#, r#"+r+x"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+r+x"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"a.txt"#, r#"x ds|7|False|[]|{}|None"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r(name="x", s="v", i=3, b=True, l=["a","b"], d={"k":"v"}, lab="//:f.txt")
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: None,
        printed: &[r#"attrs v 3 True ["a", "b"] {"k": "v"}"#],
        mapping: &[
            (r#"x"#, r#"+r+x"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+r+x"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"a.txt"#, r#"x v|3|True|["a", "b"]|{"k": "v"}|f.txt"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r(name="x", s=1)
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: Some(
            r#"in call to 'r' repo rule with name 'x', expected value of type 'string' for attribute 's', but got 1 (int)"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r(name="x", bogus=1)
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: Some(
            r#"in call to 'r' repo rule with name 'x', unknown attribute 'bogus' provided"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r(name="x", i="s")
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: Some(
            r#"in call to 'r' repo rule with name 'x', expected value of type 'int' for attribute 'i', but got "s" (string)"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r(name="x", l="notalist")
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: Some(
            r#"in call to 'r' repo rule with name 'x', expected value of type 'list(string)' for attribute 'l', but got "notalist" (string)"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r(name="x", lab=1)
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: Some(
            r#"in call to 'r' repo rule with name 'x', expected value of type 'string' for attribute 'lab', but got 1 (int)"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r2 = use_repo_rule("//:r.bzl", "r2")
r2(name="x")
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: Some(
            r#"in call to 'r2' repo rule with name 'x', mandatory attribute 's' isn't being specified"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r(name="x", dev_dependency=True)
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: None,
        printed: &[r#"attrs ds 7 False [] {}"#],
        mapping: &[
            (r#"x"#, r#"+r+x"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+r+x"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"a.txt"#, r#"x ds|7|False|[]|{}|None"#),
            ],
        )],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "notarule")
r(name="x")
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: Some(
            r#"//:r.bzl does not export a repository_rule called notarule, yet its use is requested at MODULE.bazel:3:2"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "nothing")
r(name="x")
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@x"#],
        error: Some(
            r#"//:r.bzl does not export a repository_rule called nothing, yet its use is requested at MODULE.bazel:3:2"#,
        ),
        printed: &[],
        mapping: &[],
        repos: &[],
    },
    ExtRow {
        files: &[
            (
                r#"MODULE.bazel"#,
                r#"module(name="probe")
r = use_repo_rule("//:r.bzl", "r")
r2 = use_repo_rule("//:r.bzl", "r2")
r(name="x")
r2(name="y", s="q")
"#,
            ),
            (
                r#"r.bzl"#,
                r#"def _impl(ctx):
    ctx.file("BUILD.bazel", "filegroup(name='all')")
    ctx.file("a.txt", str(ctx.attr.s) + "|" + str(ctx.attr.i) + "|" + str(ctx.attr.b) + "|" + str(ctx.attr.l) + "|" + str(ctx.attr.d) + "|" + str(ctx.attr.lab.name if ctx.attr.lab else None))
    print("attrs", ctx.attr.s, ctx.attr.i, ctx.attr.b, ctx.attr.l, ctx.attr.d)
r = repository_rule(_impl, attrs={"s": attr.string(default="ds"), "i": attr.int(default=7), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
r2 = repository_rule(_impl, attrs={"s": attr.string(mandatory=True), "i": attr.int(), "b": attr.bool(), "l": attr.string_list(), "d": attr.string_dict(), "lab": attr.label()})
notrule = 1
"#,
            ),
            (r#"f.txt"#, r#""#),
        ],
        fetch: &[r#"@y"#],
        error: None,
        printed: &[r#"attrs q 0 False [] {}"#],
        mapping: &[
            (r#"x"#, r#"+r+x"#),
            (r#"y"#, r#"+r2+y"#),
            (r#""#, r#""#),
            (r#"probe"#, r#""#),
            (r#"bazel_tools"#, r#"bazel_tools"#),
        ],
        repos: &[(
            r#"+r2+y"#,
            &[
                (r#"BUILD.bazel"#, r#"x filegroup(name='all')"#),
                (r#"a.txt"#, r#"x q|0|False|[]|{}|None"#),
            ],
        )],
    },
];
