load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "fjfj-remote",
    srcs = glob(["src/**/*.rs"]),
    compile_data = glob(["testdata/**"]),
    rustc_flags = ["--check-cfg=cfg(kani)", "--check-cfg=cfg(test)"],
    crate_name = "fjfj_remote",
    edition = "2024",
    version = "0.0.1",
    deps = [
        "@crates//:anyhow",
        "@crates//:bazel-remote-apis",
        "@crates//:hex",
        "@crates//:prost",
        "@crates//:sha2",
        "@crates//:thiserror",
        "@crates//:tokio",
        "@crates//:tracing",
        "@crates//:zstd",
    ],
)

rust_test(
    name = "fjfj-remote_test",
    crate = ":fjfj-remote",
    rustc_flags = ["--check-cfg=cfg(kani)", "--check-cfg=cfg(test)"],
    deps = ["@crates//:serde_json"],
)
