module(name = "root", version = "0")
bazel_dep(name = "yk0", version = "1.0")
bazel_dep(name = "yk1", version = "1.0")
bazel_dep(name = "yk2", version = "1.0")
bazel_dep(name = "yk3", version = "1.0")
bazel_dep(name = "yk4", version = "1.0")
bazel_dep(name = "yk5", version = "1.0")
bazel_dep(name = "yk6", version = "1.0")
bazel_dep(name = "yk7", version = "1.0")
bazel_dep(name = "yk8", version = "1.0")
bazel_dep(name = "yk9", version = "1.0")
bazel_dep(name = "yk10", version = "1.0")
bazel_dep(name = "yk11", version = "1.0")
