//! Actions that cannot both be in a build: two that make the same file but
//! differ, and two whose outputs one is inside the other. Bazel refuses them
//! when every target has been analysed and before any action runs; two equal
//! actions are one, shared by the targets that registered them.

use crate::action::{Action, ActionKind};
use crate::artifact::Artifact;
use crate::expand::label_text;
use std::collections::BTreeMap;

/// Whether `a` and `b`, which make the same file, are the same action and so
/// one: they differ only in the target that registered them.
fn shared(a: &Action, b: &Action) -> bool {
    a.mnemonic == b.mnemonic
        && a.progress_message == b.progress_message
        && a.kind == b.kind
        && a.inputs == b.inputs
        && a.outputs == b.outputs
}

/// How Bazel names an output in a message: relative to its root.
fn root_relative(artifact: &Artifact) -> &str {
    &artifact.path
}

/// What each pair of `actions` that cannot be together says, as the text after
/// `ERROR: `, in the order of the files. Probed on Bazel 9.2.0, which also
/// writes the Java class and the digest of each action, which fjfj has no
/// counterpart for and so leaves out.
pub fn conflicts(actions: &[Action]) -> Vec<String> {
    let mut by_output: BTreeMap<String, Vec<&Action>> = BTreeMap::new();
    for action in actions {
        for output in &action.outputs {
            let at = by_output.entry(output.exec_path()).or_default();
            if !at.iter().any(|earlier| std::ptr::eq(*earlier, action)) {
                at.push(action);
            }
        }
    }
    let mut messages = Vec::new();
    for (path, made_by) in &by_output {
        let first = made_by[0];
        if made_by.iter().all(|other| shared(first, other)) {
            continue;
        }
        // The newest first, and the targets last in order first, as Bazel
        // lists them.
        let mut newest_first: Vec<&Action> = made_by.iter().rev().copied().collect();
        newest_first.sort_by_key(|a| std::cmp::Reverse(label_text(&a.owner)));
        let output = first
            .outputs
            .iter()
            .find(|o| o.exec_path() == *path)
            .expect("an output of the action");
        let unique = |items: Vec<String>| {
            let mut seen: Vec<String> = Vec::new();
            for item in items {
                if !seen.contains(&item) {
                    seen.push(item);
                }
            }
            seen.join(", ")
        };
        let owners = unique(
            newest_first
                .iter()
                .map(|a| label_text(&a.owner))
                .collect::<Vec<_>>(),
        );
        let kinds = unique(
            newest_first
                .iter()
                .map(|a| format!("{} rule", a.owner_kind))
                .collect::<Vec<_>>(),
        );
        let mnemonics = unique(newest_first.iter().map(|a| a.mnemonic.clone()).collect());
        let progress = unique(
            newest_first
                .iter()
                .filter_map(|a| a.progress_message.clone())
                .collect(),
        );
        let inputs_equal = made_by.iter().all(|a| a.inputs == first.inputs);
        let outputs_equal = made_by.iter().all(|a| a.outputs == first.outputs);
        let mut text = format!(
            "file '{}' is generated by these conflicting actions:\nLabel: {owners}\nRuleClass: {kinds}\nMnemonic: {mnemonics}\n",
            root_relative(output)
        );
        // Bazel says so of actions of one kind that can be shared.
        if !mnemonics.contains(", ") {
            text.push_str("IsShareable: true\n");
        }
        if !progress.is_empty() {
            text.push_str(&format!("Progress message: {progress}\n"));
        }
        text.push_str(&format!(
            "PrimaryOutput: File:[[<execution_root>]{}]{}\n",
            output.root.prefix, output.path
        ));
        text.push_str(&format!(
            "MandatoryInputs: {}\nOutputs: {}",
            if inputs_equal { "are equal" } else { "differ" },
            if outputs_equal { "are equal" } else { "differ" },
        ));
        messages.push(text);
    }
    // An output inside another: the file that is a directory of the other.
    let paths: Vec<&String> = by_output.keys().collect();
    for (at, outer) in paths.iter().enumerate() {
        for inner in &paths[at + 1..] {
            let Some(rest) = inner.strip_prefix(outer.as_str()) else {
                // Sorted, so nothing after this can be inside `outer`.
                break;
            };
            if !rest.starts_with('/') {
                continue;
            }
            // The manifest in a runfiles tree is made by what makes the tree.
            if by_output[*outer].iter().any(|a| {
                matches!(
                    a.kind,
                    ActionKind::RunfilesTree | ActionKind::SymlinkTree { .. }
                )
            }) {
                continue;
            }
            let owner = |path: &String| label_text(&by_output[path][0].owner);
            messages.push(format!(
                "One of the output paths '{inner}' (belonging to {}) and '{outer}' (belonging to {}) is a prefix of the other. These actions cannot be simultaneously present; please rename one of the output files or build just one of them",
                owner(inner),
                owner(outer)
            ));
        }
    }
    messages
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Label, Root};

    fn action(owner: &str, path: &str, contents: &str) -> Action {
        Action {
            owner: Label {
                repo: String::new(),
                package: String::new(),
                name: owner.into(),
            },
            owner_kind: "r".into(),
            location: String::new(),
            configuration: "k8-fastbuild".into(),
            mnemonic: "FileWrite".into(),
            progress_message: None,
            kind: ActionKind::WriteFile {
                contents: contents.as_bytes().to_vec(),
                executable: false,
            },
            inputs: Vec::new(),
            input_set: None,
            outputs: vec![Artifact {
                root: Root::derived("bazel-out/k8-fastbuild/bin"),
                path: path.into(),
                tree: false,
                symlink: false,
            }],
            exec_group: None,
        }
    }

    /// Probed with two rules that write the same file.
    #[test]
    fn two_actions_that_differ_and_make_one_file_conflict() {
        let found = conflicts(&[action("a", "same.txt", "1"), action("b", "same.txt", "2")]);
        assert_eq!(
            found,
            [
                "file 'same.txt' is generated by these conflicting actions:\nLabel: //:b, //:a\nRuleClass: r rule\nMnemonic: FileWrite\nIsShareable: true\nPrimaryOutput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]same.txt\nMandatoryInputs: are equal\nOutputs: are equal"
            ]
        );
    }

    #[test]
    fn two_equal_actions_are_one_shared() {
        let found = conflicts(&[action("c", "same.txt", "1"), action("d", "same.txt", "1")]);
        assert!(found.is_empty());
    }

    /// Probed: Bazel names the two in either order from one run to the next.
    #[test]
    fn an_output_inside_another_conflicts() {
        let found = conflicts(&[action("g", "x.txt", "1"), action("h", "x.txt/y", "1")]);
        assert_eq!(
            found,
            [
                "One of the output paths 'bazel-out/k8-fastbuild/bin/x.txt/y' (belonging to //:h) and 'bazel-out/k8-fastbuild/bin/x.txt' (belonging to //:g) is a prefix of the other. These actions cannot be simultaneously present; please rename one of the output files or build just one of them"
            ]
        );
        // A name that only starts the same is not inside it.
        assert!(conflicts(&[action("g", "x.txt", "1"), action("h", "x.txt2", "1")]).is_empty());
    }
}
