[package]
name = "fjfj-exec"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
tokio.workspace = true
futures.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
fjfj-bazel-compat.workspace = true
fjfj-graph.workspace = true
fjfj-sandbox.workspace = true
fjfj-remote.workspace = true

[dev-dependencies]
tempfile.workspace = true
