[package]
name = "fjfj-repo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fjfj-archive.workspace = true
hex.workspace = true
sha2.workspace = true
base64.workspace = true
fjfj-bzlmod.workspace = true
fjfj-graph.workspace = true
fjfj-loading.workspace = true
fjfj-starlark.workspace = true
reqwest.workspace = true
serde_json.workspace = true
starlark.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
regex.workspace = true
tempfile.workspace = true
