//! `module_ctx` and running a module extension (buildfiji-mum.8.4).
//!
//! [`run_module_extension`] runs the implementation of a `module_extension()`
//! (buildfiji-mum.8.1) over what the modules of the graph wrote for it,
//! and returns the repositories it made by calling repository rules. The
//! local operations are `repository_ctx`'s (buildfiji-mum.8.2), shared; the
//! rest is what is specific to extensions.
//!
//! What Bazel 9.2.0 does, all read off probes:
//!
//! - **Tags.** Every tag a module wrote is checked against its tag class
//!   before the implementation runs, and an error says where the tag was
//!   written: `in 'tag' tag, unknown attribute 'x' provided`, `... mandatory
//!   attribute 'x' isn't being specified`, `... expected value of type 'string'
//!   for attribute 'x', but got 1 (int)`; a tag of a class the extension does
//!   not have is `The module extension defined at FILE:L:C does not have a tag
//!   class named X, but its use is attempted at MODULE.bazel:L:C`. A tag gets
//!   the default of each attribute it left out.
//! - **`mctx.modules`** is the modules that use the extension, each a
//!   `bazel_module` with `name`, `version` (`""` for none), `is_root` and
//!   `tags`, whose attribute for each tag class of the extension (whether or
//!   not it was used) is the list of that module's tags of the class in
//!   written order. A tag prints as `'tag' tag at MODULE.bazel:3:8`.
//!   `mctx.is_dev_dependency(tag)` and `mctx.root_module_has_non_dev_dependency`
//!   say what `dev_dependency` said.
//! - **Repositories.** Calling a repository rule from the implementation
//!   makes one: the name must be a string (`expected string for attribute
//!   'name', got 'NoneType'`) of letters, digits and `-_.` starting with a
//!   letter or digit, not used already by the extension (`A repo named a is
//!   already generated by this module extension at FILE:L:C`), and every other
//!   attribute must be one the rule has, of the right type (`in call to 'repo'
//!   repo rule with name 'a', unknown attribute 'x' provided`); the call
//!   returns `None`.
//! - **The working directory** is one of the extension's own, which a file
//!   written with `mctx.file` goes in and a relative path is relative to. A
//!   label in the main repository is the file, and `mctx.watch` of a path
//!   under the working directory is refused, as for a repository rule.
//! - `mctx.facts` prints `Facts({})`; `mctx.extension_metadata(...)` returns an
//!   inert object.

use crate::args::fatal;
use crate::attr::view as attribute_view;
use crate::decl::{P, bind_checked, is_bool, is_dict, is_sequence, p};
use crate::ext::{module_extension_arg, module_extension_def_location, tag_class_arg};
use crate::label::{BzlEval, RepoMappings, caller, resolve as resolve_label};
use crate::repo_ctx::{
    RepoAttr, RepoEnv, RepoError, RepoOs, RepoPath, op_execute, op_file, op_getenv, op_path,
    op_read, op_report_progress, op_watch, op_which, os_members_for,
};
use allocative::Allocative;
use fjfj_graph::Label;
use fjfj_graph::LabelParseError;
use fjfj_graph::rule::{AttrFlag, AttrType, AttrValue};
use starlark::environment::{FrozenModule, Methods, MethodsBuilder, MethodsStatic, Module};
use starlark::eval::{Arguments, Evaluator};
use starlark::starlark_module;
use starlark::starlark_simple_value;
use starlark::values::dict::{AllocDict, DictRef};
use starlark::values::list::{AllocList, ListRef};
use starlark::values::none::NoneType;
use starlark::values::tuple::TupleRef;
use starlark::values::{Heap, NoSerialize, ProvidesStaticType, StarlarkValue, Value, ValueLike};
use starlark_derive::starlark_value;
use std::cell::RefCell;
use std::fmt;
use std::sync::Arc;

// ---- what a run is given --------------------------------------------------------------

/// A value in a tag a module wrote: the data a `MODULE.bazel` can hold.
#[derive(Debug, Clone, PartialEq)]
pub enum TagValue {
    None,
    Bool(bool),
    Int(i64),
    String(String),
    List(Vec<TagValue>),
    Dict(Vec<(TagValue, TagValue)>),
}

impl TagValue {
    /// The value as Starlark writes it.
    fn repr(&self) -> String {
        match self {
            TagValue::None => "None".to_owned(),
            TagValue::Bool(true) => "True".to_owned(),
            TagValue::Bool(false) => "False".to_owned(),
            TagValue::Int(i) => i.to_string(),
            TagValue::String(s) => format!("{s:?}"),
            TagValue::List(items) => format!(
                "[{}]",
                items
                    .iter()
                    .map(TagValue::repr)
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            TagValue::Dict(items) => format!(
                "{{{}}}",
                items
                    .iter()
                    .map(|(k, v)| format!("{}: {}", k.repr(), v.repr()))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
        }
    }

    fn type_name(&self) -> &'static str {
        match self {
            TagValue::None => "NoneType",
            TagValue::Bool(_) => "bool",
            TagValue::Int(_) => "int",
            TagValue::String(_) => "string",
            TagValue::List(_) => "list",
            TagValue::Dict(_) => "dict",
        }
    }

    /// Read a Starlark value, if it is one the data can hold.
    pub(crate) fn from_value(value: Value<'_>) -> Option<TagValue> {
        if value.is_none() {
            return Some(TagValue::None);
        }
        if let Some(b) = value.unpack_bool() {
            return Some(TagValue::Bool(b));
        }
        if let Some(s) = value.unpack_str() {
            return Some(TagValue::String(s.to_owned()));
        }
        // A `Label` is the canonical label it stands for.
        if let Some(label) = value.downcast_ref::<crate::label::StarlarkLabel>() {
            return Some(TagValue::String(label.canonical()));
        }
        if let Some(i) = value.unpack_i32() {
            return Some(TagValue::Int(i.into()));
        }
        if let Some(list) = ListRef::from_value(value) {
            let items = list
                .iter()
                .map(TagValue::from_value)
                .collect::<Option<Vec<_>>>()?;
            return Some(TagValue::List(items));
        }
        if let Some(tuple) = TupleRef::from_value(value) {
            let items = tuple
                .iter()
                .map(TagValue::from_value)
                .collect::<Option<Vec<_>>>()?;
            return Some(TagValue::List(items));
        }
        if let Some(dict) = DictRef::from_value(value) {
            let items = dict
                .iter()
                .map(|(k, v)| Some((TagValue::from_value(k)?, TagValue::from_value(v)?)))
                .collect::<Option<Vec<_>>>()?;
            return Some(TagValue::Dict(items));
        }
        None
    }
}

/// One call of a tag class in a `MODULE.bazel`.
#[derive(Debug, Clone, PartialEq)]
pub struct TagUse {
    pub class: String,
    pub attrs: Vec<(String, TagValue)>,
    pub dev_dependency: bool,
    /// Where it was written, `MODULE.bazel:3:8`.
    pub location: String,
}

/// What one module wrote for the extension.
#[derive(Debug, Clone, PartialEq)]
pub struct ModuleUse {
    pub name: String,
    pub version: String,
    pub is_root: bool,
    /// The module's repository, which a label in a tag is relative to.
    pub repo: String,
    pub tags: Vec<TagUse>,
}

/// What an extension is run over.
#[derive(Debug, Clone, PartialEq)]
pub struct ExtensionInput {
    /// The modules that use it, the root module first.
    pub modules: Vec<ModuleUse>,
    /// The root module uses it other than as a dev dependency.
    pub root_has_non_dev_dependency: bool,
    /// What a previous run kept with `extension_metadata(facts = ...)`.
    pub facts: Vec<(String, FactValue)>,
}

/// A repository an extension made.
#[derive(Debug, Clone, PartialEq)]
pub struct GeneratedRepo {
    pub name: String,
    /// The repository rule, as `FILE%NAME` (`@@repo//pkg:file.bzl%rule`).
    pub rule: String,
    /// The attributes the call gave (not the defaults), `name` left out.
    pub attrs: Vec<(String, RepoAttr)>,
    /// Where it was made, `ext.bzl:6:9`.
    pub location: String,
}

/// What running an extension made.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ExtensionOutput {
    pub repos: Vec<GeneratedRepo>,
    /// What the implementation read from outside, in the order it first did.
    pub recorded: Vec<crate::repo_ctx::RecordedInput>,
    /// What `extension_metadata()` said, if it was returned.
    pub metadata: Option<MetadataOut>,
    /// `extension_metadata(reproducible = True)` was returned: the result is the
    /// same wherever it is run, and is not kept in the lockfile.
    pub reproducible: bool,
    /// The extension was declared `os_dependent` and/or `arch_dependent`.
    pub os_dependent: bool,
    pub arch_dependent: bool,
}

/// What a running extension collects, reached through the evaluator's `extra`.
#[derive(Default)]
pub(crate) struct ExtensionState {
    pub(crate) repos: Vec<GeneratedRepo>,
}

// ---- converting what was written ------------------------------------------------------

fn label_in(text: &str, repo: &str, mappings: &RepoMappings) -> Result<Label, LabelParseError> {
    resolve_label(
        text,
        fjfj_graph::LabelContext { repo, package: "" },
        repo,
        mappings,
    )
    .map(crate::label::StarlarkLabel::into_label)
}

/// `value` as an attribute of type `ty`, or the words for why not.
pub(crate) fn plain_to_attr(
    ty: AttrType,
    value: &TagValue,
    repo: &str,
    mappings: &RepoMappings,
) -> Result<RepoAttr, String> {
    let mismatch = || format!("{} ({})", value.repr(), value.type_name());
    let strings = |items: &[TagValue]| -> Option<Vec<String>> {
        items
            .iter()
            .map(|i| match i {
                TagValue::String(s) => Some(s.clone()),
                _ => None,
            })
            .collect()
    };
    let label = |text: &str| label_in(text, repo, mappings).map_err(|e| e.to_string());
    let fail = || Err(mismatch());
    Ok(match (ty, value) {
        (AttrType::Bool, TagValue::Bool(b)) => RepoAttr::Bool(*b),
        (AttrType::Int, TagValue::Int(i)) => RepoAttr::Int(*i),
        (AttrType::String, TagValue::String(s)) => RepoAttr::String(s.clone()),
        (AttrType::Label, TagValue::String(s)) => RepoAttr::Label(label(s)?),
        (AttrType::StringList, TagValue::List(items)) => match strings(items) {
            Some(items) => RepoAttr::StringList(items),
            None => return fail(),
        },
        (AttrType::IntList, TagValue::List(items)) => {
            let ints: Option<Vec<i64>> = items
                .iter()
                .map(|i| match i {
                    TagValue::Int(i) => Some(*i),
                    _ => None,
                })
                .collect();
            match ints {
                Some(items) => RepoAttr::IntList(items),
                None => return fail(),
            }
        }
        (AttrType::LabelList, TagValue::List(items)) => match strings(items) {
            Some(items) => RepoAttr::LabelList(
                items
                    .iter()
                    .map(|s| label(s))
                    .collect::<Result<Vec<_>, _>>()?,
            ),
            None => return fail(),
        },
        (AttrType::StringDict, TagValue::Dict(items)) => {
            let pairs: Option<Vec<(String, String)>> = items
                .iter()
                .map(|(k, v)| match (k, v) {
                    (TagValue::String(k), TagValue::String(v)) => Some((k.clone(), v.clone())),
                    _ => None,
                })
                .collect();
            match pairs {
                Some(pairs) => RepoAttr::StringDict(pairs),
                None => return fail(),
            }
        }
        (AttrType::StringKeyedLabelDict, TagValue::Dict(items)) => {
            let mut pairs = Vec::new();
            for (k, v) in items {
                match (k, v) {
                    (TagValue::String(k), TagValue::String(v)) => {
                        pairs.push((k.clone(), label(v)?));
                    }
                    _ => return fail(),
                }
            }
            RepoAttr::StringKeyedLabelDict(pairs)
        }
        (AttrType::LabelKeyedStringDict, TagValue::Dict(items)) => {
            let mut pairs = Vec::new();
            for (k, v) in items {
                match (k, v) {
                    (TagValue::String(k), TagValue::String(v)) => {
                        pairs.push((label(k)?, v.clone()));
                    }
                    _ => return fail(),
                }
            }
            RepoAttr::LabelKeyedStringDict(pairs)
        }
        (AttrType::LabelListDict, TagValue::Dict(items)) => {
            let mut pairs = Vec::new();
            for (k, v) in items {
                match (k, v) {
                    (TagValue::String(k), TagValue::List(v)) => {
                        let labels = strings(v)
                            .ok_or_else(mismatch)?
                            .iter()
                            .map(|s| label(s))
                            .collect::<Result<Vec<_>, _>>()?;
                        pairs.push((k.clone(), labels));
                    }
                    _ => return fail(),
                }
            }
            RepoAttr::LabelListDict(pairs)
        }
        (AttrType::StringListDict, TagValue::Dict(items)) => {
            let pairs: Option<Vec<(String, Vec<String>)>> = items
                .iter()
                .map(|(k, v)| match (k, v) {
                    (TagValue::String(k), TagValue::List(v)) => Some((k.clone(), strings(v)?)),
                    _ => None,
                })
                .collect();
            match pairs {
                Some(pairs) => RepoAttr::StringListDict(pairs),
                None => return fail(),
            }
        }
        _ => return fail(),
    })
}

/// The attribute definitions of a tag class or repository rule: for each name
/// its type, default and whether it is mandatory.
struct AttrSpec {
    name: String,
    ty: AttrType,
    default: Option<AttrValue>,
    mandatory: bool,
}

fn specs_of(attrs: Option<Value<'_>>) -> Vec<AttrSpec> {
    let Some(dict) = attrs.and_then(DictRef::from_value) else {
        return Vec::new();
    };
    dict.iter()
        .filter_map(|(name, descriptor)| {
            let view = attribute_view(descriptor)?;
            Some(AttrSpec {
                name: name.unpack_str()?.to_owned(),
                ty: view.def.ty,
                default: view.def.default.clone(),
                mandatory: view.def.flags.contains(&AttrFlag::Mandatory),
            })
        })
        .collect()
}

fn default_attr(spec: &AttrSpec) -> Option<RepoAttr> {
    let Some(value) = spec.default.clone().or_else(|| spec.ty.zero()) else {
        return Some(RepoAttr::None);
    };
    Some(match value {
        AttrValue::Bool(b) => RepoAttr::Bool(b),
        AttrValue::Int(i) => RepoAttr::Int(i64::from(i)),
        AttrValue::String(s) => RepoAttr::String(s),
        AttrValue::StringList(items) => RepoAttr::StringList(items),
        AttrValue::IntList(items) => RepoAttr::IntList(items.into_iter().map(i64::from).collect()),
        AttrValue::Label(label) => RepoAttr::Label(label),
        AttrValue::LabelList(labels) => RepoAttr::LabelList(labels),
        AttrValue::StringDict(items) => RepoAttr::StringDict(items),
        AttrValue::StringListDict(items) => RepoAttr::StringListDict(items),
        AttrValue::StringKeyedLabelDict(items) => RepoAttr::StringKeyedLabelDict(items),
        AttrValue::LabelKeyedStringDict(items) => RepoAttr::LabelKeyedStringDict(items),
        AttrValue::LabelListDict(items) => RepoAttr::LabelListDict(items),
        _ => return None,
    })
}

/// Check a tag against its class and fill in what it left out.
/// The strings of a tag attribute of type `ty` that are read as labels.
fn label_texts(ty: AttrType, value: &TagValue) -> Vec<&str> {
    fn text(v: &TagValue) -> Option<&str> {
        match v {
            TagValue::String(s) => Some(s.as_str()),
            _ => None,
        }
    }
    match (ty, value) {
        (AttrType::Label, v) => text(v).into_iter().collect(),
        (AttrType::LabelList, TagValue::List(items)) => {
            items.iter().filter_map(|i| text(i)).collect()
        }
        (AttrType::StringKeyedLabelDict | AttrType::LabelListDict, TagValue::Dict(items)) => {
            let mut out = Vec::new();
            for (_, v) in items {
                match v {
                    TagValue::List(items) => out.extend(items.iter().filter_map(|i| text(i))),
                    other => out.extend(text(other)),
                }
            }
            out
        }
        (AttrType::LabelKeyedStringDict, TagValue::Dict(items)) => {
            items.iter().filter_map(|(k, _)| text(k)).collect()
        }
        _ => Vec::new(),
    }
}

fn check_tag(
    class_attrs: &[AttrSpec],
    tag: &TagUse,
    repo: &str,
    mappings: &RepoMappings,
    recorder: &crate::repo_ctx::Recorder,
) -> Result<Vec<(String, RepoAttr)>, String> {
    let prefix = format!("in '{}' tag, ", tag.class);
    for (name, _) in &tag.attrs {
        if !class_attrs.iter().any(|a| &a.name == name) {
            return Err(format!("{prefix}unknown attribute '{name}' provided"));
        }
    }
    let mut out = Vec::new();
    for spec in class_attrs {
        match tag.attrs.iter().find(|(n, _)| n == &spec.name) {
            Some((_, value)) => {
                let converted = plain_to_attr(spec.ty, value, repo, mappings).map_err(|why| {
                    format!(
                        "{prefix}expected value of type '{}' for attribute '{}', but got {why}",
                        spec.ty.name(),
                        spec.name
                    )
                })?;
                // The repo names a label in a tag uses are looked up in the
                // mapping of the module that wrote it.
                for text in label_texts(spec.ty, value) {
                    if let Some(apparent) = crate::label::apparent_repo(text) {
                        recorder.push(crate::repo_ctx::RecordedInput::RepoMapping {
                            repo: repo.to_owned(),
                            apparent: apparent.to_owned(),
                            canonical: mappings
                                .find_apparent(repo, apparent)
                                .unwrap_or_else(|| "\\0".to_owned()),
                        });
                    }
                }
                out.push((spec.name.clone(), converted));
            }
            None if spec.mandatory => {
                return Err(format!(
                    "{prefix}mandatory attribute '{}' isn't being specified",
                    spec.name
                ));
            }
            None => {
                if let Some(default) = default_attr(spec) {
                    out.push((spec.name.clone(), default));
                }
            }
        }
    }
    Ok(out)
}

// ---- the values -----------------------------------------------------------------------

/// A tag, checked and with its defaults.
#[derive(Debug)]
struct TagData {
    class: String,
    attrs: Vec<(String, RepoAttr)>,
    dev: bool,
    location: String,
}

#[derive(Debug)]
struct ModuleData {
    name: String,
    version: String,
    is_root: bool,
    tags: Vec<TagData>,
}

/// What a running extension is given.
struct ExtData {
    modules: Vec<ModuleData>,
    /// Every tag class of the extension, in declaration order.
    classes: Vec<String>,
    root_has_non_dev: bool,
    facts: Arc<Vec<(String, FactValue)>>,
}

/// `module_ctx`.
#[derive(ProvidesStaticType, NoSerialize, Allocative)]
pub(crate) struct ModuleCtx {
    #[allocative(skip)]
    pub(crate) env: Arc<RepoEnv>,
    #[allocative(skip)]
    data: Arc<ExtData>,
}

starlark_simple_value!(ModuleCtx);

impl fmt::Debug for ModuleCtx {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("ModuleCtx")
    }
}

impl fmt::Display for ModuleCtx {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "<unknown object com.google.devtools.build.lib.bazel.bzlmod.ModuleExtensionContext>"
        )
    }
}

#[starlark_value(type = "module_ctx")]
impl<'v> StarlarkValue<'v> for ModuleCtx {
    fn get_methods() -> Option<&'static Methods> {
        static RES: MethodsStatic = MethodsStatic::new("module_ctx", mctx_members);
        Some(RES.methods())
    }
}

fn this_ctx<'v>(this: Value<'v>) -> &'v ModuleCtx {
    this.downcast_ref::<ModuleCtx>()
        .expect("a module_ctx method is called on one")
}

/// `bazel_module`.
#[derive(ProvidesStaticType, NoSerialize, Allocative)]
struct BazelModule {
    #[allocative(skip)]
    data: Arc<ExtData>,
    index: usize,
}

starlark_simple_value!(BazelModule);

impl fmt::Debug for BazelModule {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("BazelModule")
    }
}

impl fmt::Display for BazelModule {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "<unknown object com.google.devtools.build.lib.bazel.bzlmod.StarlarkBazelModule>"
        )
    }
}

#[starlark_value(type = "bazel_module")]
impl<'v> StarlarkValue<'v> for BazelModule {
    fn get_attr(&self, attribute: &str, heap: Heap<'v>) -> Option<Value<'v>> {
        let module = &self.data.modules[self.index];
        match attribute {
            "name" => Some(heap.alloc_str(&module.name).to_value()),
            "version" => Some(heap.alloc_str(&module.version).to_value()),
            "is_root" => Some(Value::new_bool(module.is_root)),
            "tags" => Some(heap.alloc(BazelModuleTags {
                data: Arc::clone(&self.data),
                index: self.index,
            })),
            _ => None,
        }
    }

    fn dir_attr(&self) -> Vec<String> {
        ["is_root", "name", "tags", "version"]
            .map(str::to_owned)
            .to_vec()
    }
}

/// `bazel_module_tags`: a module's tags by class.
#[derive(ProvidesStaticType, NoSerialize, Allocative)]
struct BazelModuleTags {
    #[allocative(skip)]
    data: Arc<ExtData>,
    index: usize,
}

starlark_simple_value!(BazelModuleTags);

impl fmt::Debug for BazelModuleTags {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("BazelModuleTags")
    }
}

impl fmt::Display for BazelModuleTags {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "<unknown object com.google.devtools.build.lib.bazel.bzlmod.StarlarkBazelModule$Tags>"
        )
    }
}

#[starlark_value(type = "bazel_module_tags")]
impl<'v> StarlarkValue<'v> for BazelModuleTags {
    fn get_attr(&self, attribute: &str, heap: Heap<'v>) -> Option<Value<'v>> {
        if !self.data.classes.iter().any(|c| c == attribute) {
            return None;
        }
        let module = &self.data.modules[self.index];
        let tags: Vec<Value<'v>> = module
            .tags
            .iter()
            .enumerate()
            .filter(|(_, t)| t.class == attribute)
            .map(|(at, _)| {
                heap.alloc(BazelModuleTag {
                    data: Arc::clone(&self.data),
                    module: self.index,
                    tag: at,
                })
            })
            .collect();
        Some(heap.alloc(AllocList(tags)))
    }

    fn dir_attr(&self) -> Vec<String> {
        self.data.classes.clone()
    }
}

/// `bazel_module_tag`: one tag, with its attributes.
#[derive(ProvidesStaticType, NoSerialize, Allocative)]
struct BazelModuleTag {
    #[allocative(skip)]
    data: Arc<ExtData>,
    module: usize,
    tag: usize,
}

starlark_simple_value!(BazelModuleTag);

impl BazelModuleTag {
    fn tag(&self) -> &TagData {
        &self.data.modules[self.module].tags[self.tag]
    }
}

impl fmt::Debug for BazelModuleTag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("BazelModuleTag")
    }
}

/// What `repr` shows, and so what a list of tags shows.
impl fmt::Display for BazelModuleTag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "<unknown object com.google.devtools.build.lib.bazel.bzlmod.TypeCheckedTag>"
        )
    }
}

#[starlark_value(type = "bazel_module_tag")]
impl<'v> StarlarkValue<'v> for BazelModuleTag {
    fn collect_str(&self, collector: &mut String) {
        let tag = self.tag();
        collector.push_str(&format!("'{}' tag at {}", tag.class, tag.location));
    }

    fn get_attr(&self, attribute: &str, heap: Heap<'v>) -> Option<Value<'v>> {
        self.tag()
            .attrs
            .iter()
            .find(|(name, _)| name == attribute)
            .map(|(_, value)| value.to_value(heap))
    }

    fn dir_attr(&self) -> Vec<String> {
        let mut names: Vec<String> = self.tag().attrs.iter().map(|(n, _)| n.clone()).collect();
        names.sort();
        names
    }
}

/// `mctx.facts`: what a previous run of the extension kept with
/// `extension_metadata(facts = ...)`. Read with `get(key, default)`, `facts[key]`
/// (`None` for a key that is not there) and `key in facts`; it has no length.
#[derive(Debug, ProvidesStaticType, NoSerialize, Allocative)]
struct Facts {
    #[allocative(skip)]
    data: Arc<Vec<(String, FactValue)>>,
}

starlark_simple_value!(Facts);

impl fmt::Display for Facts {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Facts(<opaque, inspect with print()>)")
    }
}

fn alloc_fact<'v>(heap: Heap<'v>, fact: &FactValue) -> Value<'v> {
    match fact {
        FactValue::None => Value::new_none(),
        FactValue::Bool(b) => Value::new_bool(*b),
        FactValue::Int(i) => heap.alloc(*i),
        FactValue::Float(f) => heap.alloc(starlark::values::float::StarlarkFloat(*f)),
        FactValue::String(s) => heap.alloc(s.as_str()),
        FactValue::List(items) => heap.alloc(AllocList(
            items
                .iter()
                .map(|i| alloc_fact(heap, i))
                .collect::<Vec<_>>(),
        )),
        FactValue::Dict(items) => heap.alloc(AllocDict(
            items
                .iter()
                .map(|(k, v)| (heap.alloc(k.as_str()), alloc_fact(heap, v)))
                .collect::<Vec<_>>(),
        )),
    }
}

impl Facts {
    fn lookup<'v>(&self, heap: Heap<'v>, key: &str) -> Option<Value<'v>> {
        self.data
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| alloc_fact(heap, v))
    }
}

#[starlark_module]
fn facts_methods(builder: &mut MethodsBuilder) {
    /// `facts.get(key, default = None)`.
    fn get<'v>(
        this: Value<'v>,
        #[starlark(require = pos)] key: &str,
        #[starlark(require = pos)] default: Option<Value<'v>>,
        heap: Heap<'v>,
    ) -> starlark::Result<Value<'v>> {
        let facts = this.downcast_ref::<Facts>().expect("a Facts method");
        Ok(facts
            .lookup(heap, key)
            .or(default)
            .unwrap_or_else(Value::new_none))
    }
}

#[starlark_value(type = "Facts")]
impl<'v> StarlarkValue<'v> for Facts {
    fn get_methods() -> Option<&'static Methods> {
        static RES: MethodsStatic = MethodsStatic::new("Facts", facts_methods);
        Some(RES.methods())
    }

    fn at(&self, index: Value<'v>, heap: Heap<'v>) -> starlark::Result<Value<'v>> {
        let key = index.unpack_str().unwrap_or_default();
        Ok(self.lookup(heap, key).unwrap_or_else(Value::new_none))
    }

    fn is_in(&self, other: Value<'v>) -> starlark::Result<bool> {
        Ok(other
            .unpack_str()
            .is_some_and(|key| self.data.iter().any(|(k, _)| k == key)))
    }
}

/// Which repositories `extension_metadata()` says the root module should
/// import with `use_repo`.
#[derive(Debug, Clone, PartialEq, Eq, Allocative)]
pub enum MetaDeps {
    /// Not said.
    Unset,
    /// `"all"`: every repository the extension generates.
    All,
    List(Vec<String>),
}

/// A value of the `facts` an extension keeps in `MODULE.bazel.lock`.
#[derive(Debug, Clone, PartialEq, Allocative)]
pub enum FactValue {
    None,
    Bool(bool),
    Int(i64),
    Float(f64),
    String(String),
    List(Vec<FactValue>),
    Dict(Vec<(String, FactValue)>),
}

/// What `extension_metadata()` said.
#[derive(Debug, Clone, PartialEq, Allocative)]
pub struct MetadataOut {
    pub reproducible: bool,
    pub direct: MetaDeps,
    pub dev: MetaDeps,
    pub facts: Vec<(String, FactValue)>,
}

fn fact_value(value: Value<'_>) -> Option<FactValue> {
    if value.is_none() {
        return Some(FactValue::None);
    }
    if let Some(b) = value.unpack_bool() {
        return Some(FactValue::Bool(b));
    }
    if let Some(s) = value.unpack_str() {
        return Some(FactValue::String(s.to_owned()));
    }
    if let Some(i) = value.unpack_i32() {
        return Some(FactValue::Int(i.into()));
    }
    if let Some(f) = value.downcast_ref::<starlark::values::float::StarlarkFloat>() {
        return Some(FactValue::Float(f.0));
    }
    if let Some(list) = ListRef::from_value(value) {
        return list
            .iter()
            .map(fact_value)
            .collect::<Option<Vec<_>>>()
            .map(FactValue::List);
    }
    if let Some(tuple) = TupleRef::from_value(value) {
        return tuple
            .iter()
            .map(fact_value)
            .collect::<Option<Vec<_>>>()
            .map(FactValue::List);
    }
    let dict = DictRef::from_value(value)?;
    dict.iter()
        .map(|(k, v)| Some((k.unpack_str()?.to_owned(), fact_value(v)?)))
        .collect::<Option<Vec<_>>>()
        .map(FactValue::Dict)
}

/// What `extension_metadata()` returns: nothing a module can look at.
#[derive(Debug, ProvidesStaticType, NoSerialize, Allocative)]
struct ExtensionMetadata {
    out: MetadataOut,
}

starlark_simple_value!(ExtensionMetadata);

impl fmt::Display for ExtensionMetadata {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "<unknown object com.google.devtools.build.lib.bazel.bzlmod.AutoValue_ModuleExtensionMetadata>"
        )
    }
}

#[starlark_value(type = "extension_metadata")]
impl<'v> StarlarkValue<'v> for ExtensionMetadata {}

#[starlark_module]
fn mctx_members(builder: &mut MethodsBuilder) {
    /// The modules that use the extension.
    #[starlark(attribute)]
    fn modules<'v>(this: Value<'v>, heap: Heap<'v>) -> starlark::Result<Value<'v>> {
        let data = &this_ctx(this).data;
        let modules: Vec<Value<'v>> = (0..data.modules.len())
            .map(|index| {
                heap.alloc(BazelModule {
                    data: Arc::clone(data),
                    index,
                })
            })
            .collect();
        Ok(heap.alloc(AllocList(modules)))
    }

    /// Whether the root module uses the extension other than as a dev dependency.
    #[starlark(attribute)]
    fn root_module_has_non_dev_dependency<'v>(this: Value<'v>) -> starlark::Result<bool> {
        Ok(this_ctx(this).data.root_has_non_dev)
    }

    /// The facts the extension recorded (none yet).
    #[starlark(attribute)]
    fn facts<'v>(this: Value<'v>, heap: Heap<'v>) -> starlark::Result<Value<'v>> {
        Ok(heap.alloc(Facts {
            data: Arc::clone(&this_ctx(this).data.facts),
        }))
    }

    /// The operating system.
    #[starlark(attribute)]
    fn os<'v>(this: Value<'v>, heap: Heap<'v>) -> starlark::Result<Value<'v>> {
        Ok(heap.alloc(os_members_for(&this_ctx(this).env)))
    }

    /// `mctx.is_dev_dependency(tag)`.
    fn is_dev_dependency<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<bool> {
        const PARAMS: &[P] =
            &[p("tag", true, true, "bazel_module_tag", is_module_tag).positional_only()];
        let _ = this;
        let bound = bind_checked("is_dev_dependency", PARAMS, args, eval)?;
        let tag = bound[0]
            .and_then(|t| t.downcast_ref::<BazelModuleTag>())
            .expect("checked");
        Ok(tag.tag().dev)
    }

    /// `mctx.tag_sort_key(tag)`: nothing to sort by yet.
    fn tag_sort_key<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        let _ = (this, args, eval);
        Ok(NoneType)
    }

    /// `mctx.extension_metadata(...)`.
    fn extension_metadata<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<Value<'v>> {
        const PARAMS: &[P] = &[
            p(
                "root_module_direct_deps",
                false,
                false,
                "sequence, string, or NoneType",
                is_seq_str_or_none,
            ),
            p(
                "root_module_direct_dev_deps",
                false,
                false,
                "sequence, string, or NoneType",
                is_seq_str_or_none,
            ),
            p("reproducible", false, false, "bool", is_bool),
            p("facts", false, false, "dict", is_dict),
        ];
        let _ = this;
        let bound = bind_checked("extension_metadata", PARAMS, args, eval)?;
        let deps = |value: Option<Value<'v>>, name: &str| -> starlark::Result<MetaDeps> {
            let Some(value) = value.filter(|v| !v.is_none()) else {
                return Ok(MetaDeps::Unset);
            };
            if let Some(s) = value.unpack_str() {
                return if s == "all" {
                    Ok(MetaDeps::All)
                } else {
                    Err(fatal(
                        "root_module_direct_deps and root_module_direct_dev_deps must be None, \
                         \"all\", or a list of strings",
                    ))
                };
            }
            let items: Vec<Value<'v>> = if let Some(list) = ListRef::from_value(value) {
                list.iter().collect()
            } else if let Some(tuple) = TupleRef::from_value(value) {
                tuple.iter().collect()
            } else {
                return Err(fatal(
                    "root_module_direct_deps and root_module_direct_dev_deps must be None, \
                     \"all\", or a list of strings",
                ));
            };
            let mut names = Vec::new();
            for (i, item) in items.iter().enumerate() {
                let Some(s) = item.unpack_str() else {
                    return Err(fatal(format!(
                        "at index {i} of {name}, got element of type {}, want string",
                        item.get_type()
                    )));
                };
                names.push(s.to_owned());
            }
            Ok(MetaDeps::List(names))
        };
        let direct = deps(bound[0], "root_module_direct_deps")?;
        let dev = deps(bound[1], "root_module_direct_dev_deps")?;
        let empty = |d: &MetaDeps| matches!(d, MetaDeps::List(l) if l.is_empty());
        if (direct == MetaDeps::All && !empty(&dev)) || (dev == MetaDeps::All && !empty(&direct)) {
            return Err(fatal(
                "if one of root_module_direct_deps and root_module_direct_dev_deps is \"all\", \
                 the other must be an empty list",
            ));
        }
        if (direct == MetaDeps::Unset) != (dev == MetaDeps::Unset) {
            return Err(fatal(
                "root_module_direct_deps and root_module_direct_dev_deps must both be specified \
                 or both be unspecified",
            ));
        }
        let mut seen: Vec<&str> = Vec::new();
        if let MetaDeps::List(names) = &direct {
            for name in names {
                if seen.contains(&name.as_str()) {
                    return Err(fatal(format!(
                        "in root_module_direct_deps: duplicate entry '{name}'"
                    )));
                }
                seen.push(name);
            }
        }
        if let MetaDeps::List(names) = &dev {
            let mut own: Vec<&str> = Vec::new();
            for name in names {
                if seen.contains(&name.as_str()) {
                    return Err(fatal(format!(
                        "in root_module_direct_dev_deps: entry '{name}' is also in \
                         root_module_direct_deps"
                    )));
                }
                if own.contains(&name.as_str()) {
                    return Err(fatal(format!(
                        "in root_module_direct_dev_deps: duplicate entry '{name}'"
                    )));
                }
                own.push(name);
            }
        }
        let facts = match bound[3] {
            Some(dict) => DictRef::from_value(dict)
                .map(|d| {
                    d.iter()
                        .map(|(k, v)| {
                            let key = k.unpack_str().map(str::to_owned).ok_or_else(|| {
                                fatal(format!(
                                    "facts: got {} for dict key, want string",
                                    k.get_type()
                                ))
                            })?;
                            let value = fact_value(v).ok_or_else(|| {
                                fatal(format!(
                                    "facts: cannot keep a value of type {}",
                                    v.get_type()
                                ))
                            })?;
                            Ok((key, value))
                        })
                        .collect::<starlark::Result<Vec<_>>>()
                })
                .transpose()?
                .unwrap_or_default(),
            None => Vec::new(),
        };
        let reproducible = bound[2].and_then(|v| v.unpack_bool()).unwrap_or(false);
        Ok(eval.heap().alloc(ExtensionMetadata {
            out: MetadataOut {
                reproducible,
                direct,
                dev,
                facts,
            },
        }))
    }

    fn path<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<Value<'v>> {
        op_path(this, args, eval)
    }

    fn file<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        op_file(this, args, eval)
    }

    fn read<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<String> {
        op_read(this, args, eval)
    }

    fn execute<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<Value<'v>> {
        op_execute(this, args, eval)
    }

    fn which<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<Value<'v>> {
        op_which(this, args, eval)
    }

    fn getenv<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<Value<'v>> {
        op_getenv(this, args, eval)
    }

    fn report_progress<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        op_report_progress(this, args, eval)
    }

    fn watch<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        op_watch(this, args, eval)
    }

    fn download<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<Value<'v>> {
        crate::repo_download::op_download(this, args, eval)
    }

    fn download_and_extract<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<Value<'v>> {
        crate::repo_download::op_download_and_extract(this, args, eval)
    }

    fn extract<'v>(
        this: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        crate::repo_download::op_extract(this, args, eval)
    }
}

fn is_module_tag(v: Value<'_>) -> bool {
    v.get_type() == "bazel_module_tag"
}

fn is_seq_str_or_none(v: Value<'_>) -> bool {
    is_sequence(v) || v.unpack_str().is_some() || v.is_none()
}

// ---- repository rules called by the implementation ------------------------------------

/// The characters a repository's name may have: letters, digits and `-_.`,
/// starting with a letter or digit.
fn valid_repo_name(name: &str) -> bool {
    let mut chars = name.chars();
    chars.next().is_some_and(|c| c.is_ascii_alphanumeric())
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
}

/// Whether `module` has a repository rule called `name`.
pub fn has_repository_rule(module: &FrozenModule, name: &str) -> bool {
    module
        .get_any_visibility(name)
        .is_ok_and(|(value, _)| value.value().get_type() == "repository_rule")
}

/// The attributes a `use_repo_rule` call gave the repository rule `rule_name`
/// of `module`, as the rule wants them: each checked against its type (labels
/// read as written in `repo`), or Bazel's message for the first that is not.
pub fn convert_repo_attrs(
    module: &FrozenModule,
    rule_name: &str,
    repo_name: &str,
    given: &[(String, TagValue)],
    repo: &str,
    mappings: &RepoMappings,
) -> Result<Vec<(String, RepoAttr)>, String> {
    let Ok((rule, _)) = module.get_any_visibility(rule_name) else {
        return Err(format!("no repository rule named {rule_name}"));
    };
    let specs = specs_of(crate::ext::repository_rule_arg(rule.value(), "attrs"));
    let mut attrs = Vec::new();
    for (key, value) in given {
        let Some(spec) = specs.iter().find(|s| &s.name == key) else {
            return Err(format!(
                "in call to '{rule_name}' repo rule with name '{repo_name}', unknown attribute \
                 '{key}' provided"
            ));
        };
        let converted = plain_to_attr(spec.ty, value, repo, mappings).map_err(|why| {
            format!(
                "in call to '{rule_name}' repo rule with name '{repo_name}', expected value of \
                 type '{}' for attribute '{key}', but got {why}",
                spec.ty.name()
            )
        })?;
        attrs.push((key.clone(), converted));
    }
    for spec in &specs {
        if spec.mandatory && spec.name != "name" && !given.iter().any(|(n, _)| n == &spec.name) {
            return Err(format!(
                "in call to '{rule_name}' repo rule with name '{repo_name}', mandatory attribute \
                 '{}' isn't being specified",
                spec.name
            ));
        }
    }
    Ok(attrs)
}

/// Whether a module extension is running in `eval`.
pub(crate) fn extension_running(eval: &Evaluator<'_, '_, '_>) -> bool {
    eval.extra
        .and_then(|e| e.downcast_ref::<BzlEval>())
        .is_some_and(|e| e.extension.is_some())
}

/// Whether `module` has a module extension called `name`.
pub fn has_module_extension(module: &FrozenModule, name: &str) -> bool {
    module
        .get_any_visibility(name)
        .is_ok_and(|(value, _)| value.value().get_type() == "ModuleExtension")
}

/// A repository rule called while an extension runs: make the repository.
pub(crate) fn call_repository_rule<'v>(
    rule_value: Value<'v>,
    rule_id: String,
    function: &str,
    args: &Arguments<'v, '_>,
    eval: &mut Evaluator<'v, '_, '_>,
) -> starlark::Result<Option<Value<'v>>> {
    let Some(state) = eval
        .extra
        .and_then(|e| e.downcast_ref::<BzlEval>())
        .and_then(|e| e.extension.as_ref())
    else {
        return Ok(None);
    };
    if args.positions(eval.heap())?.next().is_some() {
        return Err(fatal("unexpected positional arguments"));
    }
    let specs = specs_of(crate::ext::repository_rule_arg(rule_value, "attrs"));
    let mut given: Vec<(String, TagValue)> = Vec::new();
    for (key, value) in args.names_map()?.iter() {
        let value = TagValue::from_value(*value).ok_or_else(|| {
            fatal(format!(
                "in call to '{function}' repo rule, unsupported value of type '{}' for attribute \
                 '{}'",
                value.get_type(),
                key.as_str()
            ))
        })?;
        // `None` is an attribute that was not given.
        if matches!(value, TagValue::None) && key.as_str() != "name" {
            continue;
        }
        given.push((key.as_str().to_owned(), value));
    }
    let name = match given.iter().find(|(n, _)| n == "name") {
        Some((_, TagValue::String(name))) => name.clone(),
        Some((_, other)) => {
            return Err(fatal(format!(
                "expected string for attribute 'name', got '{}'",
                other.type_name()
            )));
        }
        None => {
            return Err(fatal(
                "expected string for attribute 'name', got 'NoneType'",
            ));
        }
    };
    if !valid_repo_name(&name) {
        return Err(fatal(format!(
            "invalid user-provided repo name '{name}': valid names may contain only A-Z, a-z, \
             0-9, '-', '_', '.', and must start with a letter or a number"
        )));
    }
    let here = crate::exports::paren_location(eval);
    {
        let state = state.borrow();
        if let Some(first) = state.repos.iter().find(|r| r.name == name) {
            return Err(fatal(format!(
                "A repo named {name} is already generated by this module extension at {}",
                first.location
            )));
        }
    }
    let (file, mappings) = caller(eval, function)?;
    let mut attrs = Vec::new();
    for (key, value) in &given {
        if key == "name" {
            continue;
        }
        let Some(spec) = specs.iter().find(|s| &s.name == key) else {
            return Err(fatal(format!(
                "in call to '{function}' repo rule with name '{name}', unknown attribute '{key}' \
                 provided"
            )));
        };
        let converted = plain_to_attr(spec.ty, value, &file.repo, mappings).map_err(|why| {
            fatal(format!(
                "in call to '{function}' repo rule with name '{name}', expected value of type \
                 '{}' for attribute '{key}', but got {why}",
                spec.ty.name()
            ))
        })?;
        attrs.push((key.clone(), converted));
    }
    for spec in &specs {
        if spec.mandatory && spec.name != "name" && !given.iter().any(|(n, _)| n == &spec.name) {
            return Err(fatal(format!(
                "in call to '{function}' repo rule with name '{name}', mandatory attribute '{}' \
                 isn't being specified",
                spec.name
            )));
        }
    }
    state.borrow_mut().repos.push(GeneratedRepo {
        name,
        rule: rule_id,
        attrs,
        location: here,
    });
    Ok(Some(Value::new_none()))
}

// ---- running an extension -------------------------------------------------------------

/// Run the extension `extension_name` of `module` (`extension_id` is how a
/// message names it, `@@//:ext.bzl%ext`) over `input`, with `env`
/// for what its context does to the file system, and return the repositories
/// it made. `print` gets what it prints.
pub fn run_module_extension(
    module: &FrozenModule,
    extension_name: &str,
    extension_id: &str,
    input: ExtensionInput,
    env: RepoEnv,
    mappings: &RepoMappings,
    print: Option<&dyn starlark::PrintHandler>,
) -> Result<ExtensionOutput, RepoError> {
    let err = |message: String| RepoError { message };
    let extension = module
        .get_any_visibility(extension_name)
        .map(|(value, _)| value)
        .map_err(|_| err(format!("no module extension named {extension_name}")))?;
    let recorder = env.recorded.clone();
    let env = Arc::new(env);
    Module::with_temp_heap(|scratch| {
        scratch.frozen_heap().add_reference(extension.owner());
        let ext_value = extension
            .value()
            .unpack_frozen()
            .expect("a global is frozen")
            .to_value();
        let implementation = module_extension_arg(ext_value, "implementation")
            .ok_or_else(|| err(format!("{extension_name} is not a module extension")))?;
        let classes_value = module_extension_arg(ext_value, "tag_classes");
        let classes: Vec<(String, Vec<AttrSpec>)> = classes_value
            .and_then(DictRef::from_value)
            .map(|dict| {
                dict.iter()
                    .filter_map(|(name, class)| {
                        Some((
                            name.unpack_str()?.to_owned(),
                            specs_of(tag_class_arg(class, "attrs")),
                        ))
                    })
                    .collect()
            })
            .unwrap_or_default();
        let defined_at = module_extension_def_location(ext_value).unwrap_or_default();
        let mut modules = Vec::new();
        for used in &input.modules {
            let mut tags = Vec::new();
            for tag in &used.tags {
                let Some((_, specs)) = classes.iter().find(|(name, _)| name == &tag.class) else {
                    return Err(err(format!(
                        "The module extension defined at {defined_at} does not have a tag class \
                         named {}, but its use is attempted at {}",
                        tag.class, tag.location
                    )));
                };
                let attrs = check_tag(specs, tag, &used.repo, mappings, &recorder).map_err(err)?;
                tags.push(TagData {
                    class: tag.class.clone(),
                    attrs,
                    dev: tag.dev_dependency,
                    location: tag.location.clone(),
                });
            }
            modules.push(ModuleData {
                name: used.name.clone(),
                version: used.version.clone(),
                is_root: used.is_root,
                tags,
            });
        }
        let data = Arc::new(ExtData {
            modules,
            classes: classes.iter().map(|(n, _)| n.clone()).collect(),
            root_has_non_dev: input.root_has_non_dev_dependency,
            facts: Arc::new(input.facts.clone()),
        });
        let mut running = BzlEval::running(mappings);
        running.extension = Some(RefCell::new(ExtensionState::default()));
        running.recorder = Some(recorder.clone());
        let mut eval = Evaluator::new(&scratch);
        eval.extra = Some(&running);
        if let Some(print) = print {
            eval.set_print_handler(print);
        }
        let ctx = scratch.heap().alloc(ModuleCtx {
            env: Arc::clone(&env),
            data,
        });
        let returned = eval
            .eval_function(implementation, &[ctx], &[])
            .map_err(|e| err(format!("{e}")))?;
        if !returned.is_none() && returned.get_type() != "extension_metadata" {
            return Err(err(format!(
                "expected module extension {extension_id} to return None or extension_metadata, \
                 got {}",
                returned.get_type()
            )));
        }
        let metadata = returned
            .downcast_ref::<ExtensionMetadata>()
            .map(|m| m.out.clone());
        let reproducible = metadata.as_ref().is_some_and(|m| m.reproducible);
        drop(eval);
        let repos = running
            .extension
            .take()
            .map(|s| s.into_inner().repos)
            .unwrap_or_default();
        let flag = |name: &str| {
            module_extension_arg(ext_value, name)
                .and_then(|v| v.unpack_bool())
                .unwrap_or(false)
        };
        Ok(ExtensionOutput {
            repos,
            recorded: recorder.inputs(),
            metadata,
            reproducible,
            os_dependent: flag("os_dependent"),
            arch_dependent: flag("arch_dependent"),
        })
    })
}

#[allow(dead_code)]
fn unused(_: &RepoPath, _: &RepoOs) {}
