// @generated by crates/fjfj-graph/probes/gen_native_rules.py from native_rules.json.
// Do not edit: rerun native_rules.py (against Bazel 9.2.0), then the generator.
//
//! The functions of the native rules in `fjfj_graph::native_rules`, which a BUILD file calls
//! as globals and a `.bzl` as `native.<rule>`.

use crate::args::fatal;
use crate::instantiate::{call_rule, native_schema};
use fjfj_graph::native_rules;
use starlark::environment::GlobalsBuilder;
use starlark::eval::{Arguments, Evaluator};
use starlark::starlark_module;
use starlark::values::none::NoneType;

const REMOVED: &str = "\n         This rule has been removed from Bazel. Please add a `load()` statement for it.\n         This can also be done automatically by running:\n         buildifier --lint=fix <path-to-BUILD-or-bzl-file>\n         ";

#[starlark_module]
pub(crate) fn generated_native_rules(builder: &mut GlobalsBuilder) {
    fn action_listener<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::ACTION_LISTENER),
            "action_listener",
            None,
            args,
            eval,
        )
    }
    fn cc_libc_top_alias<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::CC_LIBC_TOP_ALIAS),
            "cc_libc_top_alias",
            None,
            args,
            eval,
        )
    }
    fn config_feature_flag<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::CONFIG_FEATURE_FLAG),
            "config_feature_flag",
            None,
            args,
            eval,
        )
    }
    fn config_setting<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::CONFIG_SETTING),
            "config_setting",
            None,
            args,
            eval,
        )
    }
    fn constraint_setting<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::CONSTRAINT_SETTING),
            "constraint_setting",
            None,
            args,
            eval,
        )
    }
    fn constraint_value<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::CONSTRAINT_VALUE),
            "constraint_value",
            None,
            args,
            eval,
        )
    }
    fn environment<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::ENVIRONMENT),
            "environment",
            None,
            args,
            eval,
        )
    }
    fn extra_action<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::EXTRA_ACTION),
            "extra_action",
            None,
            args,
            eval,
        )
    }
    fn genquery<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::GENQUERY),
            "genquery",
            None,
            args,
            eval,
        )
    }
    fn genrule<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::GENRULE),
            "genrule",
            None,
            args,
            eval,
        )
    }
    fn java_binary<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_BINARY),
            "java_binary",
            None,
            args,
            eval,
        )
    }
    fn java_import<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_IMPORT),
            "java_import",
            None,
            args,
            eval,
        )
    }
    fn java_library<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_LIBRARY),
            "java_library",
            None,
            args,
            eval,
        )
    }
    fn java_package_configuration<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_PACKAGE_CONFIGURATION),
            "java_package_configuration",
            None,
            args,
            eval,
        )
    }
    fn java_plugin<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_PLUGIN),
            "java_plugin",
            None,
            args,
            eval,
        )
    }
    fn java_plugins_flag_alias<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_PLUGINS_FLAG_ALIAS),
            "java_plugins_flag_alias",
            None,
            args,
            eval,
        )
    }
    fn java_runtime<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_RUNTIME),
            "java_runtime",
            None,
            args,
            eval,
        )
    }
    fn java_test<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_TEST),
            "java_test",
            None,
            args,
            eval,
        )
    }
    fn java_toolchain<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::JAVA_TOOLCHAIN),
            "java_toolchain",
            None,
            args,
            eval,
        )
    }
    fn label_flag<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::LABEL_FLAG),
            "label_flag",
            None,
            args,
            eval,
        )
    }
    fn label_setting<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::LABEL_SETTING),
            "label_setting",
            None,
            args,
            eval,
        )
    }
    fn platform<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::PLATFORM),
            "platform",
            None,
            args,
            eval,
        )
    }
    fn starlark_doc_extract<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::STARLARK_DOC_EXTRACT),
            "starlark_doc_extract",
            None,
            args,
            eval,
        )
    }
    fn test_suite<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::TEST_SUITE),
            "test_suite",
            None,
            args,
            eval,
        )
    }
    fn toolchain<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::TOOLCHAIN),
            "toolchain",
            None,
            args,
            eval,
        )
    }
    fn toolchain_type<'v>(
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<NoneType> {
        call_rule(
            &native_schema(&native_rules::TOOLCHAIN_TYPE),
            "toolchain_type",
            None,
            args,
            eval,
        )
    }
    fn cc_binary<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn cc_import<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn cc_library<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn cc_shared_library<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn cc_static_library<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn cc_test<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn cc_toolchain<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn cc_toolchain_alias<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn fdo_prefetch_hints<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn fdo_profile<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn memprof_profile<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn objc_import<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn objc_library<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
    fn propeller_optimize<'v>(
        #[allow(unused_variables)] args: &Arguments<'v, '_>,
    ) -> starlark::Result<NoneType> {
        Err(fatal(REMOVED))
    }
}
